--------------------------------------------------------
--  文件已创建 - 星期六-六月-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MDM_PHASE
--------------------------------------------------------

  CREATE TABLE "MDM_PHASE" ("ID" VARCHAR2(36), "PHASE_NAME" VARCHAR2(50), "PHASE_CODE" VARCHAR2(50), "PHASE_ORDER" NUMBER(8,0), "PHASE_END_OBJ" NUMBER(3,0), "PROJ_COLLECT_SOURCE" VARCHAR2(20), "IS_MAINTAIN_BUILDING" NUMBER(1,0), "CREATE_PHASE_OBJ" VARCHAR2(2000), "CREATE_PHASE_APPROVAL_OBJ" VARCHAR2(2000), "FORM_TYPE_NAME" VARCHAR2(2000), "FORM_GROUP_CODE" VARCHAR2(2000), "MAINTAIN_BUILDING_OBJ" VARCHAR2(2000)) ;

   COMMENT ON COLUMN "MDM_PHASE"."ID" IS '主键';
   COMMENT ON COLUMN "MDM_PHASE"."PHASE_NAME" IS '阶段名称';
   COMMENT ON COLUMN "MDM_PHASE"."PHASE_CODE" IS '编码';
   COMMENT ON COLUMN "MDM_PHASE"."PHASE_ORDER" IS '阶段顺序';
   COMMENT ON COLUMN "MDM_PHASE"."PHASE_END_OBJ" IS '阶段末级对象（用于控制，在哪个对象上录入业态指标）10：地块，20：分期，30：楼栋';
   COMMENT ON COLUMN "MDM_PHASE"."PROJ_COLLECT_SOURCE" IS '项目汇总来源（10：宗地，20：分期）';
   COMMENT ON COLUMN "MDM_PHASE"."IS_MAINTAIN_BUILDING" IS '是否允许维护楼栋';
   COMMENT ON TABLE "MDM_PHASE"  IS '阶段表';
REM INSERTING into MDM_PHASE
SET DEFINE OFF;
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b6a-3c60-e053-0100007fd322','预售许可证阶段','B3',5,30,'20',0,'select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_period_phase'' else (case when cnt != 1 then ''mdm_period_phase'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project_phase'' else ''mdm_period_phase'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_project'' else (case when cnt != 1 then ''mdm_project'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project'' else ''mdm_project'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2');
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b69-3c60-e053-0100007fd322','施工许可证阶段','B2',4,30,'20',0,'select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_period_phase'' else (case when cnt != 1 then ''mdm_period_phase'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project_phase'' else ''mdm_period_phase'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_project'' else (case when cnt != 1 then ''mdm_project'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project'' else ''mdm_project'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2');
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b67-3c60-e053-0100007fd322','全盘计划版','A2',2,20,'20',0,'select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_period_phase'' else (case when cnt != 1 then ''mdm_period_phase'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project_phase'' else ''mdm_period_phase'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_project'' else (case when cnt != 1 then ''mdm_project'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project'' else ''mdm_project'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2');
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b66-3c60-e053-0100007fd322','可研版','A1',1,10,'10',0,'select    ''0''  as "objType"  from dual ','select    ''0''  as "objType"  from dual ','select    ''mdm_project_phase''  as "objType"  from dual ','select    ''mdm_project''  as "objType"  from dual ','select    ''0''  as "objType"  from dual ');
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b68-3c60-e053-0100007fd322','规划许可证阶段','B1',3,30,'20',1,'select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_period_phase'' else (case when cnt != 1 then ''mdm_period_phase'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project_phase'' else ''mdm_period_phase'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_project'' else (case when cnt != 1 then ''mdm_project'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project'' else ''mdm_project'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2');
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b6b-3c60-e053-0100007fd322','竣备阶段','B4',6,30,'20',0,'select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_period_phase'' else (case when cnt != 1 then ''mdm_period_phase'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project_phase'' else ''mdm_period_phase'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_project'' else (case when cnt != 1 then ''mdm_project'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project'' else ''mdm_project'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2');
Insert into MDM_PHASE (ID,PHASE_NAME,PHASE_CODE,PHASE_ORDER,PHASE_END_OBJ,PROJ_COLLECT_SOURCE,IS_MAINTAIN_BUILDING,CREATE_PHASE_OBJ,CREATE_PHASE_APPROVAL_OBJ,FORM_TYPE_NAME,FORM_GROUP_CODE,MAINTAIN_BUILDING_OBJ) values ('987b3331-8b6c-3c60-e053-0100007fd322','结转阶段','B5',7,30,'20',0,'select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_period_phase'' else (case when cnt != 1 then ''mdm_period_phase'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project_phase'' else ''mdm_period_phase'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''mdm_project'' else (case when cnt != 1 then ''mdm_project'' else (case when STAGE_NAME = ''无分期'' then ''mdm_project'' else ''mdm_project'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2','select (case when cnt > 1 then ''20'' else (case when cnt != 1 then ''20'' else (case when STAGE_NAME = ''无分期'' then ''0'' else ''20'' end) end) end) as "objType" from(  select distinct sp.ID, spg.STAGE_NAME, count(*) over (partition by sp.ID) as cnt from SYS_PROJECT sp left join SYS_PROJECT_STAGE spg on spg.PROJECT_ID = sp.ID where sp.ID = ''{项目ID}'' union select '''' ID, '''' STAGE_NAME ,0 cnt from dual) where ROWNUM < 2');
--------------------------------------------------------
--  DDL for Index PK_MDM_PHASE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MDM_PHASE" ON "MDM_PHASE" ("ID") ;
--------------------------------------------------------
--  Constraints for Table MDM_PHASE
--------------------------------------------------------

  ALTER TABLE "MDM_PHASE" ADD CONSTRAINT "PK_MDM_PHASE" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "MDM_PHASE" ADD CONSTRAINT "SYS_C0011190" CHECK ("ID" IS NOT NULL) ENABLE;
  ALTER TABLE "MDM_PHASE" MODIFY ("ID" NOT NULL ENABLE);
