create or replace PROCEDURE P_DWM_DT_VALUE_LIST
(
		USERID       IN VARCHAR2 --当前用户id
	 ,STATIONID    IN VARCHAR2 --当前用户岗位id
	 ,DEPARTMENTID IN VARCHAR2 --当前用户部门id
	 ,COMPANYID    IN VARCHAR2 --当前用户公司id
	 ,UNITID       IN VARCHAR2 --选择公司id
	 ,ISOPERATE    IN VARCHAR2 --是否操盘
	 ,TABSINDEX    IN INT --选择选项卡。1开始
	 ,INFO         OUT SYS_REFCURSOR
) AS
		--动态货值管理-全案动态货值-主列表
		--作者：陈丽
		--日期：2019/12/17
		DATA_AUTH_SPID VARCHAR2(200);
		BIZCODE        VARCHAR2(200);
BEGIN
		--权限编码
		BIZCODE := 'DWM.DTHZGL.03';
		P_SYS_GET_COMPANY_PROJ_SPID(USERID         => USERID,
																STATIONID      => STATIONID,
																DEPTID         => DEPARTMENTID,
																COMPANYID      => COMPANYID,
																BIZCODE        => BIZCODE,
																DATA_AUTH_SPID => DATA_AUTH_SPID);

		IF TABSINDEX = 1 THEN
				DBMS_OUTPUT.PUT_LINE('所有业态!');
		ELSIF TABSINDEX = 2 THEN
				DBMS_OUTPUT.PUT_LINE('住宅及商办!');
		ELSIF TABSINDEX = 3 THEN
				DBMS_OUTPUT.PUT_LINE('住宅!');
		ELSIF TABSINDEX = 4 THEN
				DBMS_OUTPUT.PUT_LINE('商办!');
		ELSIF TABSINDEX = 5 THEN
				DBMS_OUTPUT.PUT_LINE('车位!');
		ELSIF TABSINDEX = 6 THEN
				DBMS_OUTPUT.PUT_LINE('剩余货值表!');
				OPEN INFO FOR
						WITH TEMP_DT_VALUE (ID,COMPANY_ID, ORG_NAME, OBJ_TYPE, VALUE_DT_ALL, VALUE_REMAIN, VALUE_HAVED_SALE, VALUE_RESERVE, VALUE_IN_PROCESS, VALUE_ALLOW_SALE, VALUE_STOCK,
       VALUE_NOT_PLANNING_PERMIT, VALUE_NOT_CONSTRUCTION_PERMIT, VALUE_NOT_SALE_PERMIT, VALUE_NOT_COMPLETION, VALUE_YES_COMPLETION, VALUE_YES_SETTLEMENT, AREA_DT_ALL, AREA_REMAIN,
       AREA_HAVED_SALE, AREA_RESERVE, AREA_IN_PROCESS, AREA_ALLOW_SALE, AREA_STOCK, AREA_NOT_PLANNING_PERMIT, AREA_NOT_CONSTRUCTION_PERMIT, AREA_NOT_SALE_PERMIT, AREA_NOT_COMPLETION,
       AREA_YES_COMPLETION, AREA_YES_SETTLEMENT, TMP_1KY_VALUE, TMP_1KY_AREA, TMP_1KY_PRICE, TMP_2QP_VALUE, TMP_2QP_AREA, TMP_2QP_PRICE, TMP_3DT_TARGETVALUE, TMP_3DT_TARGETAREA,
       TMP_3DT_TARGETPRICE, CW_VALUE_DT_ALL, CW_VALUE_REMAIN, CW_VALUE_HAVED_SALE, CW_VALUE_RESERVE, CW_VALUE_IN_PROCESS, CW_VALUE_ALLOW_SALE, CW_VALUE_STOCK,
       CW_VALUE_NOT_PLANNING_PERMIT, CW_VALUE_NOT_CONSTRUCTION_PER, CW_VALUE_NOT_SALE_PERMIT, CW_VALUE_NOT_COMPLETION, CW_VALUE_YES_COMPLETION, CW_VALUE_YES_SETTLEMENT, CW_AREA_DT_ALL,
       CW_AREA_REMAIN, CW_AREA_HAVED_SALE, CW_AREA_RESERVE, CW_AREA_IN_PROCESS, CW_AREA_ALLOW_SALE, CW_AREA_STOCK, CW_AREA_NOT_PLANNING_PERMIT, CW_AREA_NOT_CONSTRUCTION_PER,
       CW_AREA_NOT_SALE_PERMIT, CW_AREA_NOT_COMPLETION, CW_AREA_YES_COMPLETION, CW_AREA_YES_SETTLEMENT, ZZ_VALUE_DT_ALL, ZZ_VALUE_REMAIN, ZZ_VALUE_HAVED_SALE, ZZ_VALUE_RESERVE,
       ZZ_VALUE_IN_PROCESS, ZZ_VALUE_ALLOW_SALE, ZZ_VALUE_STOCK, ZZ_VALUE_NOT_PLANNING_PERMIT, ZZ_VALUE_NOT_CONSTRUCTION_PER, ZZ_VALUE_NOT_SALE_PERMIT, ZZ_VALUE_NOT_COMPLETION,
       ZZ_VALUE_YES_COMPLETION, ZZ_VALUE_YES_SETTLEMENT, ZZ_AREA_DT_ALL, ZZ_AREA_REMAIN, ZZ_AREA_HAVED_SALE, ZZ_AREA_RESERVE, ZZ_AREA_IN_PROCESS, ZZ_AREA_ALLOW_SALE, ZZ_AREA_STOCK,
       ZZ_AREA_NOT_PLANNING_PERMIT, ZZ_AREA_NOT_CONSTRUCTION_PER, ZZ_AREA_NOT_SALE_PERMIT, ZZ_AREA_NOT_COMPLETION, ZZ_AREA_YES_COMPLETION, ZZ_AREA_YES_SETTLEMENT, SY_VALUE_DT_ALL,
       SY_VALUE_REMAIN, SY_VALUE_HAVED_SALE, SY_VALUE_RESERVE, SY_VALUE_IN_PROCESS, SY_VALUE_ALLOW_SALE, SY_VALUE_STOCK, SY_VALUE_NOT_PLANNING_PERMIT, SY_VALUE_NOT_CONSTRUCTION_PER,
       SY_VALUE_NOT_SALE_PERMIT, SY_VALUE_NOT_COMPLETION, SY_VALUE_YES_COMPLETION, SY_VALUE_YES_SETTLEMENT, SY_AREA_DT_ALL, SY_AREA_REMAIN, SY_AREA_HAVED_SALE, SY_AREA_RESERVE,
       SY_AREA_IN_PROCESS, SY_AREA_ALLOW_SALE, SY_AREA_STOCK, SY_AREA_NOT_PLANNING_PERMIT, SY_AREA_NOT_CONSTRUCTION_PER, SY_AREA_NOT_SALE_PERMIT, SY_AREA_NOT_COMPLETION,
       SY_AREA_YES_COMPLETION, SY_AREA_YES_SETTLEMENT, PROJ_ID, TARGET_NOW_NAME, TARGET_A_ID, TARGET_A1_ID, TARGET_A2_ID, TARGET_A3_ID, TARGET_A_VALUE, TARGET_A1_VALUE,
       TARGET_A2_VALUE, TARGET_A3_VALUE, TARGET_A_VALUE_DIFF,PARENT_ID,PROJ_COOPERATE,TAKE_DATE,IS_COMPANY,ORG_LEVEL,ORDER_CODE) AS 
       (     
SELECT A1.ID,A1.COMPANY_ID, B1.OBJ_NAME, B1.OBJ_TYPE, B1.VALUE_DT_ALL, B1.VALUE_REMAIN, B1.VALUE_HAVED_SALE, B1.VALUE_RESERVE, B1.VALUE_IN_PROCESS, B1.VALUE_ALLOW_SALE, B1.VALUE_STOCK,
       B1.VALUE_NOT_PLANNING_PERMIT, B1.VALUE_NOT_CONSTRUCTION_PERMIT, B1.VALUE_NOT_SALE_PERMIT, B1.VALUE_NOT_COMPLETION, B1.VALUE_YES_COMPLETION, B1.VALUE_YES_SETTLEMENT, B1.AREA_DT_ALL, B1.AREA_REMAIN,
       B1.AREA_HAVED_SALE, B1.AREA_RESERVE, B1.AREA_IN_PROCESS, B1.AREA_ALLOW_SALE, B1.AREA_STOCK, B1.AREA_NOT_PLANNING_PERMIT, B1.AREA_NOT_CONSTRUCTION_PERMIT, B1.AREA_NOT_SALE_PERMIT, B1.AREA_NOT_COMPLETION,
       B1.AREA_YES_COMPLETION, B1.AREA_YES_SETTLEMENT, B1.TMP_1KY_VALUE, B1.TMP_1KY_AREA, B1.TMP_1KY_PRICE, B1.TMP_2QP_VALUE, B1.TMP_2QP_AREA, B1.TMP_2QP_PRICE, B1.TMP_3DT_TARGETVALUE, B1.TMP_3DT_TARGETAREA,
       B1.TMP_3DT_TARGETPRICE, B1.CW_VALUE_DT_ALL, B1.CW_VALUE_REMAIN, B1.CW_VALUE_HAVED_SALE, B1.CW_VALUE_RESERVE, B1.CW_VALUE_IN_PROCESS, B1.CW_VALUE_ALLOW_SALE, B1.CW_VALUE_STOCK,
       B1.CW_VALUE_NOT_PLANNING_PERMIT, B1.CW_VALUE_NOT_CONSTRUCTION_PER, B1.CW_VALUE_NOT_SALE_PERMIT, B1.CW_VALUE_NOT_COMPLETION, B1.CW_VALUE_YES_COMPLETION, B1.CW_VALUE_YES_SETTLEMENT, B1.CW_AREA_DT_ALL,
       B1.CW_AREA_REMAIN, B1.CW_AREA_HAVED_SALE, B1.CW_AREA_RESERVE, B1.CW_AREA_IN_PROCESS, B1.CW_AREA_ALLOW_SALE, B1.CW_AREA_STOCK, B1.CW_AREA_NOT_PLANNING_PERMIT, B1.CW_AREA_NOT_CONSTRUCTION_PER,
       B1.CW_AREA_NOT_SALE_PERMIT, B1.CW_AREA_NOT_COMPLETION, B1.CW_AREA_YES_COMPLETION, B1.CW_AREA_YES_SETTLEMENT, B1.ZZ_VALUE_DT_ALL, B1.ZZ_VALUE_REMAIN, B1.ZZ_VALUE_HAVED_SALE, B1.ZZ_VALUE_RESERVE,
       B1.ZZ_VALUE_IN_PROCESS, B1.ZZ_VALUE_ALLOW_SALE, B1.ZZ_VALUE_STOCK, B1.ZZ_VALUE_NOT_PLANNING_PERMIT, B1.ZZ_VALUE_NOT_CONSTRUCTION_PER, B1.ZZ_VALUE_NOT_SALE_PERMIT, B1.ZZ_VALUE_NOT_COMPLETION,
       B1.ZZ_VALUE_YES_COMPLETION, B1.ZZ_VALUE_YES_SETTLEMENT, B1.ZZ_AREA_DT_ALL, B1.ZZ_AREA_REMAIN, B1.ZZ_AREA_HAVED_SALE, B1.ZZ_AREA_RESERVE, B1.ZZ_AREA_IN_PROCESS, B1.ZZ_AREA_ALLOW_SALE, B1.ZZ_AREA_STOCK,
       B1.ZZ_AREA_NOT_PLANNING_PERMIT, B1.ZZ_AREA_NOT_CONSTRUCTION_PER, B1.ZZ_AREA_NOT_SALE_PERMIT, B1.ZZ_AREA_NOT_COMPLETION, B1.ZZ_AREA_YES_COMPLETION, B1.ZZ_AREA_YES_SETTLEMENT, B1.SY_VALUE_DT_ALL,
       B1.SY_VALUE_REMAIN, B1.SY_VALUE_HAVED_SALE, B1.SY_VALUE_RESERVE, B1.SY_VALUE_IN_PROCESS, B1.SY_VALUE_ALLOW_SALE, B1.SY_VALUE_STOCK, B1.SY_VALUE_NOT_PLANNING_PERMIT, B1.SY_VALUE_NOT_CONSTRUCTION_PER,
       B1.SY_VALUE_NOT_SALE_PERMIT, B1.SY_VALUE_NOT_COMPLETION, B1.SY_VALUE_YES_COMPLETION, B1.SY_VALUE_YES_SETTLEMENT, B1.SY_AREA_DT_ALL, B1.SY_AREA_REMAIN, B1.SY_AREA_HAVED_SALE, B1.SY_AREA_RESERVE,
       B1.SY_AREA_IN_PROCESS, B1.SY_AREA_ALLOW_SALE, B1.SY_AREA_STOCK, B1.SY_AREA_NOT_PLANNING_PERMIT, B1.SY_AREA_NOT_CONSTRUCTION_PER, B1.SY_AREA_NOT_SALE_PERMIT, B1.SY_AREA_NOT_COMPLETION,
       B1.SY_AREA_YES_COMPLETION, B1.SY_AREA_YES_SETTLEMENT, B1.PROJ_ID, B1.TARGET_NOW_NAME, B1.TARGET_A_ID, B1.TARGET_A1_ID, B1.TARGET_A2_ID, B1.TARGET_A3_ID, B1.TARGET_A_VALUE, B1.TARGET_A1_VALUE,
       B1.TARGET_A2_VALUE, B1.TARGET_A3_VALUE, B1.TARGET_A_VALUE_DIFF,A1.COMPANY_ID AS PARENT_ID,NVL(A1.PROJ_COOPERATE,'操盘'),TO_CHAR(A1.PROJECT_GET_TIME,'YYYY-MM-DD') AS TAKE_DATE,0,4,a1.PROJECT_CODE
FROM   MDM_PROJECT A1
INNER  JOIN DWM_DT_VALUE B1
ON     A1.ID = B1.OBJ_ID AND B1.OBJ_TYPE = '项目'
UNION ALL
SELECT B2.ID,A2.PARENT_ID, B2.ORG_NAME, '公司', A2.VALUE_DT_ALL, A2.VALUE_REMAIN, A2.VALUE_HAVED_SALE, A2.VALUE_RESERVE, A2.VALUE_IN_PROCESS, A2.VALUE_ALLOW_SALE, A2.VALUE_STOCK,
       A2.VALUE_NOT_PLANNING_PERMIT, A2.VALUE_NOT_CONSTRUCTION_PERMIT, A2.VALUE_NOT_SALE_PERMIT, A2.VALUE_NOT_COMPLETION, A2.VALUE_YES_COMPLETION, A2.VALUE_YES_SETTLEMENT, A2.AREA_DT_ALL, A2.AREA_REMAIN,
       A2.AREA_HAVED_SALE, A2.AREA_RESERVE, A2.AREA_IN_PROCESS, A2.AREA_ALLOW_SALE, A2.AREA_STOCK, A2.AREA_NOT_PLANNING_PERMIT, A2.AREA_NOT_CONSTRUCTION_PERMIT, A2.AREA_NOT_SALE_PERMIT, A2.AREA_NOT_COMPLETION,
       A2.AREA_YES_COMPLETION, A2.AREA_YES_SETTLEMENT, A2.TMP_1KY_VALUE, A2.TMP_1KY_AREA, A2.TMP_1KY_PRICE, A2.TMP_2QP_VALUE, A2.TMP_2QP_AREA, A2.TMP_2QP_PRICE, A2.TMP_3DT_TARGETVALUE, A2.TMP_3DT_TARGETAREA,
       A2.TMP_3DT_TARGETPRICE, A2.CW_VALUE_DT_ALL, A2.CW_VALUE_REMAIN, A2.CW_VALUE_HAVED_SALE, A2.CW_VALUE_RESERVE, A2.CW_VALUE_IN_PROCESS, A2.CW_VALUE_ALLOW_SALE, A2.CW_VALUE_STOCK,
       A2.CW_VALUE_NOT_PLANNING_PERMIT, A2.CW_VALUE_NOT_CONSTRUCTION_PER, A2.CW_VALUE_NOT_SALE_PERMIT, A2.CW_VALUE_NOT_COMPLETION, A2.CW_VALUE_YES_COMPLETION, A2.CW_VALUE_YES_SETTLEMENT, A2.CW_AREA_DT_ALL,
       A2.CW_AREA_REMAIN, A2.CW_AREA_HAVED_SALE, A2.CW_AREA_RESERVE, A2.CW_AREA_IN_PROCESS, A2.CW_AREA_ALLOW_SALE, A2.CW_AREA_STOCK, A2.CW_AREA_NOT_PLANNING_PERMIT, A2.CW_AREA_NOT_CONSTRUCTION_PER,
       A2.CW_AREA_NOT_SALE_PERMIT, A2.CW_AREA_NOT_COMPLETION, A2.CW_AREA_YES_COMPLETION, A2.CW_AREA_YES_SETTLEMENT, A2.ZZ_VALUE_DT_ALL, A2.ZZ_VALUE_REMAIN, A2.ZZ_VALUE_HAVED_SALE, A2.ZZ_VALUE_RESERVE,
       A2.ZZ_VALUE_IN_PROCESS, A2.ZZ_VALUE_ALLOW_SALE, A2.ZZ_VALUE_STOCK, A2.ZZ_VALUE_NOT_PLANNING_PERMIT, A2.ZZ_VALUE_NOT_CONSTRUCTION_PER, A2.ZZ_VALUE_NOT_SALE_PERMIT, A2.ZZ_VALUE_NOT_COMPLETION,
       A2.ZZ_VALUE_YES_COMPLETION, A2.ZZ_VALUE_YES_SETTLEMENT, A2.ZZ_AREA_DT_ALL, A2.ZZ_AREA_REMAIN, A2.ZZ_AREA_HAVED_SALE, A2.ZZ_AREA_RESERVE, A2.ZZ_AREA_IN_PROCESS, A2.ZZ_AREA_ALLOW_SALE, A2.ZZ_AREA_STOCK,
       A2.ZZ_AREA_NOT_PLANNING_PERMIT, A2.ZZ_AREA_NOT_CONSTRUCTION_PER, A2.ZZ_AREA_NOT_SALE_PERMIT, A2.ZZ_AREA_NOT_COMPLETION, A2.ZZ_AREA_YES_COMPLETION, A2.ZZ_AREA_YES_SETTLEMENT, A2.SY_VALUE_DT_ALL,
       A2.SY_VALUE_REMAIN, A2.SY_VALUE_HAVED_SALE, A2.SY_VALUE_RESERVE, A2.SY_VALUE_IN_PROCESS, A2.SY_VALUE_ALLOW_SALE, A2.SY_VALUE_STOCK, A2.SY_VALUE_NOT_PLANNING_PERMIT, A2.SY_VALUE_NOT_CONSTRUCTION_PER,
       A2.SY_VALUE_NOT_SALE_PERMIT, A2.SY_VALUE_NOT_COMPLETION, A2.SY_VALUE_YES_COMPLETION, A2.SY_VALUE_YES_SETTLEMENT, A2.SY_AREA_DT_ALL, A2.SY_AREA_REMAIN, A2.SY_AREA_HAVED_SALE, A2.SY_AREA_RESERVE,
       A2.SY_AREA_IN_PROCESS, A2.SY_AREA_ALLOW_SALE, A2.SY_AREA_STOCK, A2.SY_AREA_NOT_PLANNING_PERMIT, A2.SY_AREA_NOT_CONSTRUCTION_PER, A2.SY_AREA_NOT_SALE_PERMIT, A2.SY_AREA_NOT_COMPLETION,
       A2.SY_AREA_YES_COMPLETION, A2.SY_AREA_YES_SETTLEMENT, A2.PROJ_ID, A2.TARGET_NOW_NAME, A2.TARGET_A_ID, A2.TARGET_A1_ID, A2.TARGET_A2_ID, A2.TARGET_A3_ID, A2.TARGET_A_VALUE, A2.TARGET_A1_VALUE,
       A2.TARGET_A2_VALUE, A2.TARGET_A3_VALUE, A2.TARGET_A_VALUE_DIFF,B2.PARENT_ID,'','',1,B2.LEVEL_RANK,b2.ORDER_CODE
FROM TEMP_DT_VALUE A2
INNER JOIN SYS_BUSINESS_UNIT B2 ON A2.PARENT_ID = B2.ID AND B2.IS_COMPANY = 1
)
            SELECT A.ID AS "id",
                   --主键id（生成树的id，唯一可以是业务id）
                   A.PARENT_ID AS "parentId",
                   --父级id（生成树父级id）
                   CASE
                       WHEN A.IS_COMPANY = 0 THEN
                        '/dwm/value-manage/value-project/detail?code=value_dtl'||CHR(38)||'isOperate=' ||
                        A.PROJ_COOPERATE || CHR(38)||'projectId=' || A.ID ||CHR(38)||
                        'projectName=' || A.ORG_NAME || CHR(38)||'projectDate=' ||
                        A.TAKE_DATE ||CHR(38) ||'tabIndex=' || TABSINDEX ||CHR(38)||
                        'pageTitle=' || A.ORG_NAME --页面标题名称
                       ELSE
                        ''
                   END AS "openUrl",
                   --详情穿透打开地址code：穿透后的列表获取数据源存储过程注册编码
                   CASE
                       WHEN A.IS_COMPANY = 0 THEN
                        '/dwm/value-manage/dynamic-volume/circular?companyId=' ||
                        A.PARENT_ID ||CHR(38) ||'projectId=' || A.ID || CHR(38)||'type=2' --companyId加载项目的公司id，项目id：默认选中的项目id，type：货值是1，货值是2
                       ELSE
                        ''
                   END AS "openVisualUrl",
                   --打开可视化地址
                   ORG_LEVEL,
                   CASE
                       WHEN ORG_LEVEL = 1 THEN
                        '#eaf6ff'
                       WHEN ORG_LEVEL = 2 THEN
                        '#ecfbee'
                       WHEN ORG_LEVEL = 3 THEN
                        '#f2eed4'
                       ELSE
                        ''
                   END AS "excelRowBgColor",
                   --数据行导出excel背景色
                   CASE
                       WHEN ORG_LEVEL = 1 THEN
                        '' || ORG_NAME
                       WHEN ORG_LEVEL = 2 THEN
                        '        ' || ORG_NAME
                       WHEN ORG_LEVEL = 3 THEN
                        '                ' || ORG_NAME
                       WHEN ORG_LEVEL = 4 THEN
                        '                        ' || ORG_NAME
                       ELSE
                        '                                ' || ORG_NAME
                   END AS "excelRowTextTreeOrgName",--文本前面加空格模仿树
                   A.ORG_NAME AS "orgName",--公司/项目
                   TO_CHAR(NVL(ROUND( SUM(A.ZZ_VALUE_REMAIN) / 10000, 2),0),'FM999,999,999,990.00') AS "projWholeDwellingValue",--项目全案剩余可售货值（S=A+B+C+D）-住宅(m2)
                   TO_CHAR(NVL(ROUND( SUM(A.SY_VALUE_REMAIN) / 10000, 2),0),'FM999,999,999,990.00') AS "projWholeBusinessValue",--项目全案剩余可售货值（S=A+B+C+D）-商业(m2)
                   TO_CHAR(NVL(ROUND( SUM(A.CW_VALUE_REMAIN) / 10000, 2),0),'FM999,999,999,990.00') AS "projWholeCarportValue",--项目全案剩余可售货值（S=A+B+C+D）-车位(个)
                   TO_CHAR(NVL(ROUND(( SUM(A.ZZ_VALUE_REMAIN)+SUM(A.CW_VALUE_REMAIN)+SUM(A.SY_VALUE_REMAIN)) / 10000,2),0),'FM999,999,999,990.00') AS "projWholeTotalValue",
                   --项目全案剩余可售货值（S=A+B+C+D）-合计(m2)

                   TO_CHAR(NVL(ROUND( SUM(A.ZZ_VALUE_NOT_PLANNING_PERMIT),0) / 10000, 2),'FM999,999,999,990.00') AS "ADwellingValue",--A未取规证的可售货值-住宅(m2)
                   TO_CHAR(NVL(ROUND( SUM(A.SY_VALUE_NOT_PLANNING_PERMIT),0) / 10000, 2),'FM999,999,999,990.00') AS "ABusinessValue",--A未取规证的可售货值-商业(m2)
                   TO_CHAR(NVL(ROUND( SUM(A.CW_VALUE_NOT_PLANNING_PERMIT),0) / 10000, 2),'FM999,999,999,990.00') AS "ACarportValue",--A未取规证的可售货值-车位(个)
                   TO_CHAR(NVL(ROUND((SUM(A.ZZ_VALUE_NOT_PLANNING_PERMIT)+SUM(A.CW_VALUE_NOT_PLANNING_PERMIT)+SUM(A.SY_VALUE_NOT_PLANNING_PERMIT)),0) / 10000,2),'FM999,999,999,990.00') AS "ATotalValue",--A未取规证的可售货值-合计(m2)
                   TO_CHAR(ROUND( NVL(SUM(A.ZZ_VALUE_NOT_CONSTRUCTION_PER),0) / 10000, 2),'FM999,999,999,990.00') AS "BDwellingValue",--B已取规证未取施工证的可售货值-住宅(m2)
                   TO_CHAR(ROUND(NVL(SUM(A.SY_VALUE_NOT_CONSTRUCTION_PER) / 10000, 2),0),'FM999,999,999,990.00') AS "BBusinessValue",--B已取规证未取施工证的可售货值-商业(m2)
                   TO_CHAR(ROUND(NVL(SUM(A.CW_VALUE_NOT_CONSTRUCTION_PER) / 10000, 2),0),'FM999,999,999,990.00') AS "BCarportValue",--B已取规证未取施工证的可售货值-车位(个)
                   TO_CHAR(NVL(ROUND((SUM(A.ZZ_VALUE_NOT_CONSTRUCTION_PER)+SUM(A.SY_VALUE_NOT_CONSTRUCTION_PER) + SUM(A.CW_VALUE_NOT_CONSTRUCTION_PER))/ 10000,2),0),'FM999,999,999,990.00') AS "BTotalValue",--B已取规证未取施工证的可售货值-合计(m2)

                   TO_CHAR(NVL(ROUND(SUM(A.ZZ_VALUE_NOT_SALE_PERMIT),0) / 10000, 2),'FM999,999,999,990.00') AS "CDwellingValue",--C已取施工证未取预售证的可售货值-住宅(m2)
                   TO_CHAR(NVL(ROUND(SUM(A.SY_VALUE_NOT_SALE_PERMIT),0) / 10000, 2),'FM999,999,999,990.00') AS "CBusinessValue",--C已取施工证未取预售证的可售货值-商业(m2)
                   TO_CHAR(NVL(ROUND(SUM(A.CW_VALUE_NOT_SALE_PERMIT),0) / 10000, 2),'FM999,999,999,990.00') AS "CCarportValue",--C已取施工证未取预售证的可售货值-车位(个)
                   TO_CHAR(NVL(ROUND((SUM(A.ZZ_VALUE_NOT_SALE_PERMIT)+SUM(A.SY_VALUE_NOT_SALE_PERMIT)+SUM(A.CW_VALUE_NOT_SALE_PERMIT)) / 10000,2),0),'FM999,999,999,990.00') AS "CTotalValue",--C已取施工证未取预售证的可售货值-合计(m2)

                   TO_CHAR(NVL(ROUND( SUM(A.ZZ_VALUE_STOCK) / 10000, 2),0),'FM999,999,999,990.00') AS "DDwellingValue",--D已取预售证未售的可售货值-住宅(m2)
                   TO_CHAR(NVL(ROUND(SUM(A.SY_VALUE_STOCK) / 10000, 2),0),'FM999,999,999,990.00') AS "DBusinessValue",--D已取预售证未售的可售货值-商业(m2)
                   TO_CHAR(NVL(ROUND(SUM(A.CW_VALUE_STOCK) / 10000, 2),0),'FM999,999,999,990.00') AS "DCarportValue",--D已取预售证未售的可售货值-车位(个)
                   TO_CHAR(NVL(ROUND((SUM(A.ZZ_VALUE_STOCK)+SUM(A.SY_VALUE_STOCK)+SUM(A.CW_VALUE_STOCK)) / 10000,2),0),'FM999,999,999,990.00') AS "DTotalValue" --D已取预售证未售的可售货值-合计(m2)
            FROM   TEMP_DT_VALUE A
            INNER JOIN (SELECT p.ID FROM SYS_BUSINESS_UNIT p WHERE p.IS_COMPANY = 1 START WITH p.id = '' || UNITID || '' CONNECT BY PRIOR p.ID = p.PARENT_ID
						           UNION ALL
											 SELECT M.ID FROM SYS_PROJECT M WHERE EXISTS (SELECT 1 FROM SYS_BUSINESS_UNIT N WHERE N.IS_COMPANY = 1 AND N.ID = M.UNIT_ID START WITH N.id = '' || UNITID || '' CONNECT BY PRIOR N.ID = N.PARENT_ID)) b ON a.id = b.id
						GROUP BY A.ID,A.ORG_NAME,A.PARENT_ID,A.IS_COMPANY,A.PROJ_COOPERATE，A.TAKE_DATE,ORG_LEVEL,A.ORDER_CODE;

		END IF;

		IF TABSINDEX = 1   THEN
				OPEN INFO FOR
				WITH TEMP_DT_VALUE (ID,COMPANY_ID, ORG_NAME, OBJ_TYPE, VALUE_DT_ALL, VALUE_REMAIN, VALUE_HAVED_SALE, VALUE_RESERVE, VALUE_IN_PROCESS, VALUE_ALLOW_SALE, VALUE_STOCK,
       VALUE_NOT_PLANNING_PERMIT, VALUE_NOT_CONSTRUCTION_PERMIT, VALUE_NOT_SALE_PERMIT, VALUE_NOT_COMPLETION, VALUE_YES_COMPLETION, VALUE_YES_SETTLEMENT, AREA_DT_ALL, AREA_REMAIN,
       AREA_HAVED_SALE, AREA_RESERVE, AREA_IN_PROCESS, AREA_ALLOW_SALE, AREA_STOCK, AREA_NOT_PLANNING_PERMIT, AREA_NOT_CONSTRUCTION_PERMIT, AREA_NOT_SALE_PERMIT, AREA_NOT_COMPLETION,
       AREA_YES_COMPLETION, AREA_YES_SETTLEMENT, TMP_1KY_VALUE, TMP_1KY_AREA, TMP_1KY_PRICE, TMP_2QP_VALUE, TMP_2QP_AREA, TMP_2QP_PRICE, TMP_3DT_TARGETVALUE, TMP_3DT_TARGETAREA,
       TMP_3DT_TARGETPRICE, CW_VALUE_DT_ALL, CW_VALUE_REMAIN, CW_VALUE_HAVED_SALE, CW_VALUE_RESERVE, CW_VALUE_IN_PROCESS, CW_VALUE_ALLOW_SALE, CW_VALUE_STOCK,
       CW_VALUE_NOT_PLANNING_PERMIT, CW_VALUE_NOT_CONSTRUCTION_PER, CW_VALUE_NOT_SALE_PERMIT, CW_VALUE_NOT_COMPLETION, CW_VALUE_YES_COMPLETION, CW_VALUE_YES_SETTLEMENT, CW_AREA_DT_ALL,
       CW_AREA_REMAIN, CW_AREA_HAVED_SALE, CW_AREA_RESERVE, CW_AREA_IN_PROCESS, CW_AREA_ALLOW_SALE, CW_AREA_STOCK, CW_AREA_NOT_PLANNING_PERMIT, CW_AREA_NOT_CONSTRUCTION_PER,
       CW_AREA_NOT_SALE_PERMIT, CW_AREA_NOT_COMPLETION, CW_AREA_YES_COMPLETION, CW_AREA_YES_SETTLEMENT, ZZ_VALUE_DT_ALL, ZZ_VALUE_REMAIN, ZZ_VALUE_HAVED_SALE, ZZ_VALUE_RESERVE,
       ZZ_VALUE_IN_PROCESS, ZZ_VALUE_ALLOW_SALE, ZZ_VALUE_STOCK, ZZ_VALUE_NOT_PLANNING_PERMIT, ZZ_VALUE_NOT_CONSTRUCTION_PER, ZZ_VALUE_NOT_SALE_PERMIT, ZZ_VALUE_NOT_COMPLETION,
       ZZ_VALUE_YES_COMPLETION, ZZ_VALUE_YES_SETTLEMENT, ZZ_AREA_DT_ALL, ZZ_AREA_REMAIN, ZZ_AREA_HAVED_SALE, ZZ_AREA_RESERVE, ZZ_AREA_IN_PROCESS, ZZ_AREA_ALLOW_SALE, ZZ_AREA_STOCK,
       ZZ_AREA_NOT_PLANNING_PERMIT, ZZ_AREA_NOT_CONSTRUCTION_PER, ZZ_AREA_NOT_SALE_PERMIT, ZZ_AREA_NOT_COMPLETION, ZZ_AREA_YES_COMPLETION, ZZ_AREA_YES_SETTLEMENT, SY_VALUE_DT_ALL,
       SY_VALUE_REMAIN, SY_VALUE_HAVED_SALE, SY_VALUE_RESERVE, SY_VALUE_IN_PROCESS, SY_VALUE_ALLOW_SALE, SY_VALUE_STOCK, SY_VALUE_NOT_PLANNING_PERMIT, SY_VALUE_NOT_CONSTRUCTION_PER,
       SY_VALUE_NOT_SALE_PERMIT, SY_VALUE_NOT_COMPLETION, SY_VALUE_YES_COMPLETION, SY_VALUE_YES_SETTLEMENT, SY_AREA_DT_ALL, SY_AREA_REMAIN, SY_AREA_HAVED_SALE, SY_AREA_RESERVE,
       SY_AREA_IN_PROCESS, SY_AREA_ALLOW_SALE, SY_AREA_STOCK, SY_AREA_NOT_PLANNING_PERMIT, SY_AREA_NOT_CONSTRUCTION_PER, SY_AREA_NOT_SALE_PERMIT, SY_AREA_NOT_COMPLETION,
       SY_AREA_YES_COMPLETION, SY_AREA_YES_SETTLEMENT, PROJ_ID, TARGET_NOW_NAME, TARGET_A_ID, TARGET_A1_ID, TARGET_A2_ID, TARGET_A3_ID, TARGET_A_VALUE, TARGET_A1_VALUE,
       TARGET_A2_VALUE, TARGET_A3_VALUE, TARGET_A_VALUE_DIFF,PARENT_ID,PROJ_COOPERATE,TAKE_DATE,IS_COMPANY,ORG_LEVEL,ORDER_CODE) AS 
       (     
SELECT A1.ID,A1.COMPANY_ID, B1.OBJ_NAME, B1.OBJ_TYPE, B1.VALUE_DT_ALL, B1.VALUE_REMAIN, B1.VALUE_HAVED_SALE, B1.VALUE_RESERVE, B1.VALUE_IN_PROCESS, B1.VALUE_ALLOW_SALE, B1.VALUE_STOCK,
       B1.VALUE_NOT_PLANNING_PERMIT, B1.VALUE_NOT_CONSTRUCTION_PERMIT, B1.VALUE_NOT_SALE_PERMIT, B1.VALUE_NOT_COMPLETION, B1.VALUE_YES_COMPLETION, B1.VALUE_YES_SETTLEMENT, B1.AREA_DT_ALL, B1.AREA_REMAIN,
       B1.AREA_HAVED_SALE, B1.AREA_RESERVE, B1.AREA_IN_PROCESS, B1.AREA_ALLOW_SALE, B1.AREA_STOCK, B1.AREA_NOT_PLANNING_PERMIT, B1.AREA_NOT_CONSTRUCTION_PERMIT, B1.AREA_NOT_SALE_PERMIT, B1.AREA_NOT_COMPLETION,
       B1.AREA_YES_COMPLETION, B1.AREA_YES_SETTLEMENT, B1.TMP_1KY_VALUE, B1.TMP_1KY_AREA, B1.TMP_1KY_PRICE, B1.TMP_2QP_VALUE, B1.TMP_2QP_AREA, B1.TMP_2QP_PRICE, B1.TMP_3DT_TARGETVALUE, B1.TMP_3DT_TARGETAREA,
       B1.TMP_3DT_TARGETPRICE, B1.CW_VALUE_DT_ALL, B1.CW_VALUE_REMAIN, B1.CW_VALUE_HAVED_SALE, B1.CW_VALUE_RESERVE, B1.CW_VALUE_IN_PROCESS, B1.CW_VALUE_ALLOW_SALE, B1.CW_VALUE_STOCK,
       B1.CW_VALUE_NOT_PLANNING_PERMIT, B1.CW_VALUE_NOT_CONSTRUCTION_PER, B1.CW_VALUE_NOT_SALE_PERMIT, B1.CW_VALUE_NOT_COMPLETION, B1.CW_VALUE_YES_COMPLETION, B1.CW_VALUE_YES_SETTLEMENT, B1.CW_AREA_DT_ALL,
       B1.CW_AREA_REMAIN, B1.CW_AREA_HAVED_SALE, B1.CW_AREA_RESERVE, B1.CW_AREA_IN_PROCESS, B1.CW_AREA_ALLOW_SALE, B1.CW_AREA_STOCK, B1.CW_AREA_NOT_PLANNING_PERMIT, B1.CW_AREA_NOT_CONSTRUCTION_PER,
       B1.CW_AREA_NOT_SALE_PERMIT, B1.CW_AREA_NOT_COMPLETION, B1.CW_AREA_YES_COMPLETION, B1.CW_AREA_YES_SETTLEMENT, B1.ZZ_VALUE_DT_ALL, B1.ZZ_VALUE_REMAIN, B1.ZZ_VALUE_HAVED_SALE, B1.ZZ_VALUE_RESERVE,
       B1.ZZ_VALUE_IN_PROCESS, B1.ZZ_VALUE_ALLOW_SALE, B1.ZZ_VALUE_STOCK, B1.ZZ_VALUE_NOT_PLANNING_PERMIT, B1.ZZ_VALUE_NOT_CONSTRUCTION_PER, B1.ZZ_VALUE_NOT_SALE_PERMIT, B1.ZZ_VALUE_NOT_COMPLETION,
       B1.ZZ_VALUE_YES_COMPLETION, B1.ZZ_VALUE_YES_SETTLEMENT, B1.ZZ_AREA_DT_ALL, B1.ZZ_AREA_REMAIN, B1.ZZ_AREA_HAVED_SALE, B1.ZZ_AREA_RESERVE, B1.ZZ_AREA_IN_PROCESS, B1.ZZ_AREA_ALLOW_SALE, B1.ZZ_AREA_STOCK,
       B1.ZZ_AREA_NOT_PLANNING_PERMIT, B1.ZZ_AREA_NOT_CONSTRUCTION_PER, B1.ZZ_AREA_NOT_SALE_PERMIT, B1.ZZ_AREA_NOT_COMPLETION, B1.ZZ_AREA_YES_COMPLETION, B1.ZZ_AREA_YES_SETTLEMENT, B1.SY_VALUE_DT_ALL,
       B1.SY_VALUE_REMAIN, B1.SY_VALUE_HAVED_SALE, B1.SY_VALUE_RESERVE, B1.SY_VALUE_IN_PROCESS, B1.SY_VALUE_ALLOW_SALE, B1.SY_VALUE_STOCK, B1.SY_VALUE_NOT_PLANNING_PERMIT, B1.SY_VALUE_NOT_CONSTRUCTION_PER,
       B1.SY_VALUE_NOT_SALE_PERMIT, B1.SY_VALUE_NOT_COMPLETION, B1.SY_VALUE_YES_COMPLETION, B1.SY_VALUE_YES_SETTLEMENT, B1.SY_AREA_DT_ALL, B1.SY_AREA_REMAIN, B1.SY_AREA_HAVED_SALE, B1.SY_AREA_RESERVE,
       B1.SY_AREA_IN_PROCESS, B1.SY_AREA_ALLOW_SALE, B1.SY_AREA_STOCK, B1.SY_AREA_NOT_PLANNING_PERMIT, B1.SY_AREA_NOT_CONSTRUCTION_PER, B1.SY_AREA_NOT_SALE_PERMIT, B1.SY_AREA_NOT_COMPLETION,
       B1.SY_AREA_YES_COMPLETION, B1.SY_AREA_YES_SETTLEMENT, B1.PROJ_ID, B1.TARGET_NOW_NAME, B1.TARGET_A_ID, B1.TARGET_A1_ID, B1.TARGET_A2_ID, B1.TARGET_A3_ID, B1.TARGET_A_VALUE, B1.TARGET_A1_VALUE,
       B1.TARGET_A2_VALUE, B1.TARGET_A3_VALUE, B1.TARGET_A_VALUE_DIFF,A1.COMPANY_ID AS PARENT_ID,NVL(A1.PROJ_COOPERATE,'操盘'),TO_CHAR(A1.PROJECT_GET_TIME,'YYYY-MM-DD') AS TAKE_DATE,0,4,a1.PROJECT_CODE
FROM   MDM_PROJECT A1
INNER  JOIN DWM_DT_VALUE B1
ON     A1.ID = B1.OBJ_ID AND B1.OBJ_TYPE = '项目'
UNION ALL
SELECT B2.ID,A2.PARENT_ID, B2.ORG_NAME, '公司', A2.VALUE_DT_ALL, A2.VALUE_REMAIN, A2.VALUE_HAVED_SALE, A2.VALUE_RESERVE, A2.VALUE_IN_PROCESS, A2.VALUE_ALLOW_SALE, A2.VALUE_STOCK,
       A2.VALUE_NOT_PLANNING_PERMIT, A2.VALUE_NOT_CONSTRUCTION_PERMIT, A2.VALUE_NOT_SALE_PERMIT, A2.VALUE_NOT_COMPLETION, A2.VALUE_YES_COMPLETION, A2.VALUE_YES_SETTLEMENT, A2.AREA_DT_ALL, A2.AREA_REMAIN,
       A2.AREA_HAVED_SALE, A2.AREA_RESERVE, A2.AREA_IN_PROCESS, A2.AREA_ALLOW_SALE, A2.AREA_STOCK, A2.AREA_NOT_PLANNING_PERMIT, A2.AREA_NOT_CONSTRUCTION_PERMIT, A2.AREA_NOT_SALE_PERMIT, A2.AREA_NOT_COMPLETION,
       A2.AREA_YES_COMPLETION, A2.AREA_YES_SETTLEMENT, A2.TMP_1KY_VALUE, A2.TMP_1KY_AREA, A2.TMP_1KY_PRICE, A2.TMP_2QP_VALUE, A2.TMP_2QP_AREA, A2.TMP_2QP_PRICE, A2.TMP_3DT_TARGETVALUE, A2.TMP_3DT_TARGETAREA,
       A2.TMP_3DT_TARGETPRICE, A2.CW_VALUE_DT_ALL, A2.CW_VALUE_REMAIN, A2.CW_VALUE_HAVED_SALE, A2.CW_VALUE_RESERVE, A2.CW_VALUE_IN_PROCESS, A2.CW_VALUE_ALLOW_SALE, A2.CW_VALUE_STOCK,
       A2.CW_VALUE_NOT_PLANNING_PERMIT, A2.CW_VALUE_NOT_CONSTRUCTION_PER, A2.CW_VALUE_NOT_SALE_PERMIT, A2.CW_VALUE_NOT_COMPLETION, A2.CW_VALUE_YES_COMPLETION, A2.CW_VALUE_YES_SETTLEMENT, A2.CW_AREA_DT_ALL,
       A2.CW_AREA_REMAIN, A2.CW_AREA_HAVED_SALE, A2.CW_AREA_RESERVE, A2.CW_AREA_IN_PROCESS, A2.CW_AREA_ALLOW_SALE, A2.CW_AREA_STOCK, A2.CW_AREA_NOT_PLANNING_PERMIT, A2.CW_AREA_NOT_CONSTRUCTION_PER,
       A2.CW_AREA_NOT_SALE_PERMIT, A2.CW_AREA_NOT_COMPLETION, A2.CW_AREA_YES_COMPLETION, A2.CW_AREA_YES_SETTLEMENT, A2.ZZ_VALUE_DT_ALL, A2.ZZ_VALUE_REMAIN, A2.ZZ_VALUE_HAVED_SALE, A2.ZZ_VALUE_RESERVE,
       A2.ZZ_VALUE_IN_PROCESS, A2.ZZ_VALUE_ALLOW_SALE, A2.ZZ_VALUE_STOCK, A2.ZZ_VALUE_NOT_PLANNING_PERMIT, A2.ZZ_VALUE_NOT_CONSTRUCTION_PER, A2.ZZ_VALUE_NOT_SALE_PERMIT, A2.ZZ_VALUE_NOT_COMPLETION,
       A2.ZZ_VALUE_YES_COMPLETION, A2.ZZ_VALUE_YES_SETTLEMENT, A2.ZZ_AREA_DT_ALL, A2.ZZ_AREA_REMAIN, A2.ZZ_AREA_HAVED_SALE, A2.ZZ_AREA_RESERVE, A2.ZZ_AREA_IN_PROCESS, A2.ZZ_AREA_ALLOW_SALE, A2.ZZ_AREA_STOCK,
       A2.ZZ_AREA_NOT_PLANNING_PERMIT, A2.ZZ_AREA_NOT_CONSTRUCTION_PER, A2.ZZ_AREA_NOT_SALE_PERMIT, A2.ZZ_AREA_NOT_COMPLETION, A2.ZZ_AREA_YES_COMPLETION, A2.ZZ_AREA_YES_SETTLEMENT, A2.SY_VALUE_DT_ALL,
       A2.SY_VALUE_REMAIN, A2.SY_VALUE_HAVED_SALE, A2.SY_VALUE_RESERVE, A2.SY_VALUE_IN_PROCESS, A2.SY_VALUE_ALLOW_SALE, A2.SY_VALUE_STOCK, A2.SY_VALUE_NOT_PLANNING_PERMIT, A2.SY_VALUE_NOT_CONSTRUCTION_PER,
       A2.SY_VALUE_NOT_SALE_PERMIT, A2.SY_VALUE_NOT_COMPLETION, A2.SY_VALUE_YES_COMPLETION, A2.SY_VALUE_YES_SETTLEMENT, A2.SY_AREA_DT_ALL, A2.SY_AREA_REMAIN, A2.SY_AREA_HAVED_SALE, A2.SY_AREA_RESERVE,
       A2.SY_AREA_IN_PROCESS, A2.SY_AREA_ALLOW_SALE, A2.SY_AREA_STOCK, A2.SY_AREA_NOT_PLANNING_PERMIT, A2.SY_AREA_NOT_CONSTRUCTION_PER, A2.SY_AREA_NOT_SALE_PERMIT, A2.SY_AREA_NOT_COMPLETION,
       A2.SY_AREA_YES_COMPLETION, A2.SY_AREA_YES_SETTLEMENT, A2.PROJ_ID, A2.TARGET_NOW_NAME, A2.TARGET_A_ID, A2.TARGET_A1_ID, A2.TARGET_A2_ID, A2.TARGET_A3_ID, A2.TARGET_A_VALUE, A2.TARGET_A1_VALUE,
       A2.TARGET_A2_VALUE, A2.TARGET_A3_VALUE, A2.TARGET_A_VALUE_DIFF,B2.PARENT_ID,'','',1,B2.LEVEL_RANK,b2.ORDER_CODE
FROM TEMP_DT_VALUE A2
INNER JOIN SYS_BUSINESS_UNIT B2 ON A2.PARENT_ID = B2.ID AND B2.IS_COMPANY = 1
)
						SELECT A.ID AS "id",
									 --主键id（生成树的id，唯一可以是业务id）
									 A.PARENT_ID AS "parentId",
									 --父级id（生成树父级id）
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/value-project/detail?code=value_dtl&isOperate=' ||
												 A.PROJ_COOPERATE || '&projectId=' || A.ID || '&projectName=' ||
												 A.ORG_NAME || '&projectDate=' || A.TAKE_DATE || '&tabIndex=' ||
												 TABSINDEX || '&pageTitle=' || A.ORG_NAME --页面标题名称
												ELSE
												 ''
										END) AS "openUrl",
									 --详情穿透打开地址code：穿透后的列表获取数据源存储过程注册编码
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/dynamic-volume/circular?companyId=' || A.PARENT_ID ||
												 '&projectId=' || A.ID || '&type=2' --companyId加载项目的公司id，项目id：默认选中的项目id，type：货量是1，货值是2
												ELSE
												 ''
										END) AS "openVisualUrl",
									 --打开可视化地址
									 ORG_LEVEL,
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '#eaf6ff'
												WHEN ORG_LEVEL = 2 THEN
												 '#ecfbee'
												WHEN ORG_LEVEL = 3 THEN
												 '#f2eed4'
												ELSE
												 ''
										END AS "excelRowBgColor",
									 --数据行导出excel背景色
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '' || ORG_NAME
												WHEN ORG_LEVEL = 2 THEN
												 '        ' || ORG_NAME
												WHEN ORG_LEVEL = 3 THEN
												 '                ' || ORG_NAME
												WHEN ORG_LEVEL = 4 THEN
												 '                        ' || ORG_NAME
												ELSE
												 '                                ' || ORG_NAME
										END AS "excelRowTextTreeOrgName",
									 --文本前面加空格模仿树
									 A.ORG_NAME AS "orgName",--公司/项目
									 --TO_CHAR(b.area_dt_all, '999,999,999,999,990.00') AS "newestBuildArea",--最新建筑面积
									 TO_CHAR( NVL(SUM(A.AREA_DT_ALL),0), '999,999,999,999,990.00') AS "targetSalesArea",--最新可售面积（不含车位）
									 TO_CHAR(NVL(SUM(A.TARGET_A1_VALUE),0),'999,999,999,999,990.00') AS "targetFeasibleWorth",--目标总货值（A）-可研版(A1)
									 TO_CHAR( NVL(SUM(A.TARGET_A2_VALUE),0),'999,999,999,999,990.00') AS "targetWholeWorth",--目标总货值（A）-全盘版(A2)
									 TO_CHAR( NVL(SUM(A.TARGET_A3_VALUE),0),'999,999,999,999,990.00') AS "targetDynamicWorth",--目标总货值（A）-动态版(A3)
									  TO_CHAR( NVL(SUM(A.TARGET_A_VALUE),0),'999,999,999,999,990.00') AS "targetNewestWorth",--目标总货值（A）-最新版(A)

/*                   TO_CHAR((SELECT SUM(A.Target_Now)
                            FROM   SYS_BUSINESS_UNIT SBU
                            LEFT   JOIN mdm_PROJECT mp  ON SBU.ID = mp.COMPANY_ID AND mp.APPROVAL_STATUS = '已审核' AND mp.IS_DELETE = 0 
                            LEFT   JOIN v_DWM_DT_VALUE DDV ON A.OBJ_ID = mP.PROJECT_ORIGINAL_ID
                            WHERE mp.PROJ_COOPERATE = (CASE WHEN ISOPERATE = '操盘' THEN '操盘'  WHEN ISOPERATE = '非操盘' THEN '不操盘' ELSE PROJ_COOPERATE END)
                            START  WITH (SBU.ID = a.id OR mp.PROJECT_ORIGINAL_ID = a.id)
                            CONNECT BY PRIOR SBU.ID = SBU.PARENT_ID)
                            ,'999,999,999,999,990.00') AS "targetNewestWorth",--目标总货值（A）-最新版(A)*/

									 TO_CHAR( round(NVL(SUM(A.value_dt_all),0)/10000,2), '999,999,999,999,990.00') AS "dynamicTotalWorth",--动态总货值(B)
									 (CASE
												WHEN round( SUM(A.value_dt_all)/10000-SUM(A.TARGET_A_VALUE),2) < -1 THEN
												 '<font color=red>' ||TO_CHAR( SUM(A.value_dt_all)/10000-SUM(A.TARGET_A_VALUE),'999,999,999,999,990.00') || '</font>'
												ELSE
												 '<font color=green>' ||TO_CHAR( SUM(A.value_dt_all)/10000-SUM(A.TARGET_A_VALUE),'999,999,999,999,990.00') || '</font>'
										END) AS "dynamicTotalWorthDifference",--总货值差额(B-A)
									 TO_CHAR( NVL(SUM(A.VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-储备货值(B1)
									 TO_CHAR( NVL(SUM(A.VALUE_IN_PROCESS),0) / 10000, '999,999,999,999,990.00') AS "inProcessTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-在途货值(B2)--修改字段holdConstructionPermit=》inTransitWorth
									 TO_CHAR(  SUM(nvl(A.VALUE_STOCK,0))/ 10000 ,'999,999,999,999,990.00') AS "stockWorth",  --动态总货值构成（B=B1+B2+B3+B4）-库存货值(B3)
									 TO_CHAR( NVL(SUM(A.VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "alreadySalesWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-已售货值(B4)
									 TO_CHAR( NVL(SUM(A.VALUE_REMAIN),0), '999,999,999,999,990.00') AS "residueWorth",
									 --剩余货值(C=B1+B2+B3)
									 TO_CHAR( NVL(( SUM(A.Value_Stock)+SUM(A.VALUE_HAVED_SALE)),0)/10000, '999,999,999,999,990.00') AS "getWorth",
									 --已领证货值(D=B3+B4)
									 (CASE
												WHEN (SUM(A.VALUE_STOCK)+SUM(A.VALUE_HAVED_SALE)) = 0 
                        THEN  '-'
												ELSE
												 TO_CHAR(NVL( SUM(A.VALUE_HAVED_SALE) / ( SUM(A.VALUE_STOCK)+SUM(A.VALUE_HAVED_SALE)),0) * 100, '999,999,999,999,990.00') || '%'
										END) AS "salesRate",
									 --去化率(E=B4/D)
									 TO_CHAR( NVL(SUM(A.VALUE_NOT_PLANNING_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "noPlanningPermitObtainedPhase",
									 --F、动态货值的各阶段分布-F0未取规证
									 TO_CHAR( NVL(SUM(A.VALUE_NOT_CONSTRUCTION_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "planningPermitObtainedOhase",
									 --F、动态货值的各阶段分布-F1规划许可证阶段
									 TO_CHAR( NVL(SUM(A.VALUE_NOT_SALE_PERMIT) ,0)/ 10000, '999,999,999,999,990.00') AS "constructionPermitOhase",
									 --F、动态货值的各阶段分布-F2施工许可证阶段
									 TO_CHAR( NVL(SUM(A.VALUE_NOT_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "PreSalePermitPhase",
									 --F、动态货值的各阶段分布-F3预售许可证阶段
									 --TO_CHAR(b.value_yes_completion / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",--F、动态货值的各阶段分布-F4竣备阶段
									 TO_CHAR( NVL(SUM(A.VALUE_YES_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",
									 --F、动态货值的各阶段分布-F4竣备阶段
									 '-' AS "carryDownPhase",
									 --F、动态货值的各阶段分布-F5结转阶段

									 TO_CHAR( NVL(SUM(A.VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveWorth",
									 --G1、储备货值的量价情况-货值（G1=a1*b1）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_RESERVE)+SUM(A.SY_AREA_RESERVE)),0), '999,999,999,999,990.00') AS "reserveCargo",
									 --G1、储备货值的量价情况-货量(a1)
									 '-' AS "reservePrice",
									 --G1、储备货值的量价情况-单价(b1)
									 TO_CHAR( NVL(SUM(A.value_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "inTransitWorth",
									 --G2、在途货值的量价情况-货值（G2=a2*b2）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_IN_PROCESS)+SUM(A.SY_AREA_IN_PROCESS)),0), '999,999,999,999,990.00') AS "inTransitCargo",
									 --G2、在途货值的量价情况-货量(a2)
									 '-' AS "inTransitPrice",
									 --G2、在途货值的量价情况-单价(b2)
									 TO_CHAR( NVL(SUM(VALUE_STOCK),0) / 10000, '999,999,999,999,990.00') AS "stockWorth",
									 --G3、库存货值的量价情况-货值（G3=a3*b3）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_STOCK) + SUM(A.SY_AREA_STOCK)),0), '999,999,999,999,990.00') AS "stockCargo",
									 --G3、库存货值的量价情况-货量(a3)
									 '-' AS "stockPrice",
									 --G3、库存货值的量价情况-单价(b3)
									 TO_CHAR( NVL(SUM(VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "soldWorth",
									 --G4、已售货值的量价情况-货值（G4=a4*b4）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_HAVED_SALE)+SUM(A.SY_AREA_HAVED_SALE)),0), '999,999,999,999,990.00') AS "soldCargo",
									 --G4、已售货值的量价情况-货量(a4)
									 '-' AS "soldPrice" --G4、已售货值的量价情况-单价(b4)
						FROM   TEMP_DT_VALUE A
            INNER JOIN (SELECT p.ID FROM SYS_BUSINESS_UNIT p WHERE p.IS_COMPANY = 1 START WITH p.id = '' || UNITID || '' CONNECT BY PRIOR p.ID = p.PARENT_ID
						           UNION ALL
											 SELECT M.ID FROM SYS_PROJECT M WHERE EXISTS (SELECT 1 FROM SYS_BUSINESS_UNIT N WHERE N.IS_COMPANY = 1 AND N.ID = M.UNIT_ID START WITH N.id = '' || UNITID || '' CONNECT BY PRIOR N.ID = N.PARENT_ID)) b ON a.id = b.id
						GROUP BY A.ID,A.ORG_NAME,A.PARENT_ID,A.IS_COMPANY,A.PROJ_COOPERATE，A.TAKE_DATE,ORG_LEVEL,A.ORDER_CODE;
		END IF;

		IF TABSINDEX = 2 THEN
				OPEN INFO FOR
				WITH TEMP_DT_VALUE (ID,COMPANY_ID, ORG_NAME, OBJ_TYPE, VALUE_DT_ALL, VALUE_REMAIN, VALUE_HAVED_SALE, VALUE_RESERVE, VALUE_IN_PROCESS, VALUE_ALLOW_SALE, VALUE_STOCK,
       VALUE_NOT_PLANNING_PERMIT, VALUE_NOT_CONSTRUCTION_PERMIT, VALUE_NOT_SALE_PERMIT, VALUE_NOT_COMPLETION, VALUE_YES_COMPLETION, VALUE_YES_SETTLEMENT, AREA_DT_ALL, AREA_REMAIN,
       AREA_HAVED_SALE, AREA_RESERVE, AREA_IN_PROCESS, AREA_ALLOW_SALE, AREA_STOCK, AREA_NOT_PLANNING_PERMIT, AREA_NOT_CONSTRUCTION_PERMIT, AREA_NOT_SALE_PERMIT, AREA_NOT_COMPLETION,
       AREA_YES_COMPLETION, AREA_YES_SETTLEMENT, TMP_1KY_VALUE, TMP_1KY_AREA, TMP_1KY_PRICE, TMP_2QP_VALUE, TMP_2QP_AREA, TMP_2QP_PRICE, TMP_3DT_TARGETVALUE, TMP_3DT_TARGETAREA,
       TMP_3DT_TARGETPRICE, CW_VALUE_DT_ALL, CW_VALUE_REMAIN, CW_VALUE_HAVED_SALE, CW_VALUE_RESERVE, CW_VALUE_IN_PROCESS, CW_VALUE_ALLOW_SALE, CW_VALUE_STOCK,
       CW_VALUE_NOT_PLANNING_PERMIT, CW_VALUE_NOT_CONSTRUCTION_PER, CW_VALUE_NOT_SALE_PERMIT, CW_VALUE_NOT_COMPLETION, CW_VALUE_YES_COMPLETION, CW_VALUE_YES_SETTLEMENT, CW_AREA_DT_ALL,
       CW_AREA_REMAIN, CW_AREA_HAVED_SALE, CW_AREA_RESERVE, CW_AREA_IN_PROCESS, CW_AREA_ALLOW_SALE, CW_AREA_STOCK, CW_AREA_NOT_PLANNING_PERMIT, CW_AREA_NOT_CONSTRUCTION_PER,
       CW_AREA_NOT_SALE_PERMIT, CW_AREA_NOT_COMPLETION, CW_AREA_YES_COMPLETION, CW_AREA_YES_SETTLEMENT, ZZ_VALUE_DT_ALL, ZZ_VALUE_REMAIN, ZZ_VALUE_HAVED_SALE, ZZ_VALUE_RESERVE,
       ZZ_VALUE_IN_PROCESS, ZZ_VALUE_ALLOW_SALE, ZZ_VALUE_STOCK, ZZ_VALUE_NOT_PLANNING_PERMIT, ZZ_VALUE_NOT_CONSTRUCTION_PER, ZZ_VALUE_NOT_SALE_PERMIT, ZZ_VALUE_NOT_COMPLETION,
       ZZ_VALUE_YES_COMPLETION, ZZ_VALUE_YES_SETTLEMENT, ZZ_AREA_DT_ALL, ZZ_AREA_REMAIN, ZZ_AREA_HAVED_SALE, ZZ_AREA_RESERVE, ZZ_AREA_IN_PROCESS, ZZ_AREA_ALLOW_SALE, ZZ_AREA_STOCK,
       ZZ_AREA_NOT_PLANNING_PERMIT, ZZ_AREA_NOT_CONSTRUCTION_PER, ZZ_AREA_NOT_SALE_PERMIT, ZZ_AREA_NOT_COMPLETION, ZZ_AREA_YES_COMPLETION, ZZ_AREA_YES_SETTLEMENT, SY_VALUE_DT_ALL,
       SY_VALUE_REMAIN, SY_VALUE_HAVED_SALE, SY_VALUE_RESERVE, SY_VALUE_IN_PROCESS, SY_VALUE_ALLOW_SALE, SY_VALUE_STOCK, SY_VALUE_NOT_PLANNING_PERMIT, SY_VALUE_NOT_CONSTRUCTION_PER,
       SY_VALUE_NOT_SALE_PERMIT, SY_VALUE_NOT_COMPLETION, SY_VALUE_YES_COMPLETION, SY_VALUE_YES_SETTLEMENT, SY_AREA_DT_ALL, SY_AREA_REMAIN, SY_AREA_HAVED_SALE, SY_AREA_RESERVE,
       SY_AREA_IN_PROCESS, SY_AREA_ALLOW_SALE, SY_AREA_STOCK, SY_AREA_NOT_PLANNING_PERMIT, SY_AREA_NOT_CONSTRUCTION_PER, SY_AREA_NOT_SALE_PERMIT, SY_AREA_NOT_COMPLETION,
       SY_AREA_YES_COMPLETION, SY_AREA_YES_SETTLEMENT, PROJ_ID, TARGET_NOW_NAME, TARGET_A_ID, TARGET_A1_ID, TARGET_A2_ID, TARGET_A3_ID, TARGET_A_VALUE, TARGET_A1_VALUE,
       TARGET_A2_VALUE, TARGET_A3_VALUE, TARGET_A_VALUE_DIFF,PARENT_ID,PROJ_COOPERATE,TAKE_DATE,IS_COMPANY,ORG_LEVEL,ORDER_CODE) AS 
       (     
SELECT A1.ID,A1.COMPANY_ID, B1.OBJ_NAME, B1.OBJ_TYPE, B1.VALUE_DT_ALL, B1.VALUE_REMAIN, B1.VALUE_HAVED_SALE, B1.VALUE_RESERVE, B1.VALUE_IN_PROCESS, B1.VALUE_ALLOW_SALE, B1.VALUE_STOCK,
       B1.VALUE_NOT_PLANNING_PERMIT, B1.VALUE_NOT_CONSTRUCTION_PERMIT, B1.VALUE_NOT_SALE_PERMIT, B1.VALUE_NOT_COMPLETION, B1.VALUE_YES_COMPLETION, B1.VALUE_YES_SETTLEMENT, B1.AREA_DT_ALL, B1.AREA_REMAIN,
       B1.AREA_HAVED_SALE, B1.AREA_RESERVE, B1.AREA_IN_PROCESS, B1.AREA_ALLOW_SALE, B1.AREA_STOCK, B1.AREA_NOT_PLANNING_PERMIT, B1.AREA_NOT_CONSTRUCTION_PERMIT, B1.AREA_NOT_SALE_PERMIT, B1.AREA_NOT_COMPLETION,
       B1.AREA_YES_COMPLETION, B1.AREA_YES_SETTLEMENT, B1.TMP_1KY_VALUE, B1.TMP_1KY_AREA, B1.TMP_1KY_PRICE, B1.TMP_2QP_VALUE, B1.TMP_2QP_AREA, B1.TMP_2QP_PRICE, B1.TMP_3DT_TARGETVALUE, B1.TMP_3DT_TARGETAREA,
       B1.TMP_3DT_TARGETPRICE, B1.CW_VALUE_DT_ALL, B1.CW_VALUE_REMAIN, B1.CW_VALUE_HAVED_SALE, B1.CW_VALUE_RESERVE, B1.CW_VALUE_IN_PROCESS, B1.CW_VALUE_ALLOW_SALE, B1.CW_VALUE_STOCK,
       B1.CW_VALUE_NOT_PLANNING_PERMIT, B1.CW_VALUE_NOT_CONSTRUCTION_PER, B1.CW_VALUE_NOT_SALE_PERMIT, B1.CW_VALUE_NOT_COMPLETION, B1.CW_VALUE_YES_COMPLETION, B1.CW_VALUE_YES_SETTLEMENT, B1.CW_AREA_DT_ALL,
       B1.CW_AREA_REMAIN, B1.CW_AREA_HAVED_SALE, B1.CW_AREA_RESERVE, B1.CW_AREA_IN_PROCESS, B1.CW_AREA_ALLOW_SALE, B1.CW_AREA_STOCK, B1.CW_AREA_NOT_PLANNING_PERMIT, B1.CW_AREA_NOT_CONSTRUCTION_PER,
       B1.CW_AREA_NOT_SALE_PERMIT, B1.CW_AREA_NOT_COMPLETION, B1.CW_AREA_YES_COMPLETION, B1.CW_AREA_YES_SETTLEMENT, B1.ZZ_VALUE_DT_ALL, B1.ZZ_VALUE_REMAIN, B1.ZZ_VALUE_HAVED_SALE, B1.ZZ_VALUE_RESERVE,
       B1.ZZ_VALUE_IN_PROCESS, B1.ZZ_VALUE_ALLOW_SALE, B1.ZZ_VALUE_STOCK, B1.ZZ_VALUE_NOT_PLANNING_PERMIT, B1.ZZ_VALUE_NOT_CONSTRUCTION_PER, B1.ZZ_VALUE_NOT_SALE_PERMIT, B1.ZZ_VALUE_NOT_COMPLETION,
       B1.ZZ_VALUE_YES_COMPLETION, B1.ZZ_VALUE_YES_SETTLEMENT, B1.ZZ_AREA_DT_ALL, B1.ZZ_AREA_REMAIN, B1.ZZ_AREA_HAVED_SALE, B1.ZZ_AREA_RESERVE, B1.ZZ_AREA_IN_PROCESS, B1.ZZ_AREA_ALLOW_SALE, B1.ZZ_AREA_STOCK,
       B1.ZZ_AREA_NOT_PLANNING_PERMIT, B1.ZZ_AREA_NOT_CONSTRUCTION_PER, B1.ZZ_AREA_NOT_SALE_PERMIT, B1.ZZ_AREA_NOT_COMPLETION, B1.ZZ_AREA_YES_COMPLETION, B1.ZZ_AREA_YES_SETTLEMENT, B1.SY_VALUE_DT_ALL,
       B1.SY_VALUE_REMAIN, B1.SY_VALUE_HAVED_SALE, B1.SY_VALUE_RESERVE, B1.SY_VALUE_IN_PROCESS, B1.SY_VALUE_ALLOW_SALE, B1.SY_VALUE_STOCK, B1.SY_VALUE_NOT_PLANNING_PERMIT, B1.SY_VALUE_NOT_CONSTRUCTION_PER,
       B1.SY_VALUE_NOT_SALE_PERMIT, B1.SY_VALUE_NOT_COMPLETION, B1.SY_VALUE_YES_COMPLETION, B1.SY_VALUE_YES_SETTLEMENT, B1.SY_AREA_DT_ALL, B1.SY_AREA_REMAIN, B1.SY_AREA_HAVED_SALE, B1.SY_AREA_RESERVE,
       B1.SY_AREA_IN_PROCESS, B1.SY_AREA_ALLOW_SALE, B1.SY_AREA_STOCK, B1.SY_AREA_NOT_PLANNING_PERMIT, B1.SY_AREA_NOT_CONSTRUCTION_PER, B1.SY_AREA_NOT_SALE_PERMIT, B1.SY_AREA_NOT_COMPLETION,
       B1.SY_AREA_YES_COMPLETION, B1.SY_AREA_YES_SETTLEMENT, B1.PROJ_ID, B1.TARGET_NOW_NAME, B1.TARGET_A_ID, B1.TARGET_A1_ID, B1.TARGET_A2_ID, B1.TARGET_A3_ID, B1.TARGET_A_VALUE, B1.TARGET_A1_VALUE,
       B1.TARGET_A2_VALUE, B1.TARGET_A3_VALUE, B1.TARGET_A_VALUE_DIFF,A1.COMPANY_ID AS PARENT_ID,NVL(A1.PROJ_COOPERATE,'操盘'),TO_CHAR(A1.PROJECT_GET_TIME,'YYYY-MM-DD') AS TAKE_DATE,0,4,a1.PROJECT_CODE
FROM   MDM_PROJECT A1
INNER  JOIN DWM_DT_VALUE B1
ON     A1.ID = B1.OBJ_ID AND B1.OBJ_TYPE = '项目'
UNION ALL
SELECT B2.ID,A2.PARENT_ID, B2.ORG_NAME, '公司', A2.VALUE_DT_ALL, A2.VALUE_REMAIN, A2.VALUE_HAVED_SALE, A2.VALUE_RESERVE, A2.VALUE_IN_PROCESS, A2.VALUE_ALLOW_SALE, A2.VALUE_STOCK,
       A2.VALUE_NOT_PLANNING_PERMIT, A2.VALUE_NOT_CONSTRUCTION_PERMIT, A2.VALUE_NOT_SALE_PERMIT, A2.VALUE_NOT_COMPLETION, A2.VALUE_YES_COMPLETION, A2.VALUE_YES_SETTLEMENT, A2.AREA_DT_ALL, A2.AREA_REMAIN,
       A2.AREA_HAVED_SALE, A2.AREA_RESERVE, A2.AREA_IN_PROCESS, A2.AREA_ALLOW_SALE, A2.AREA_STOCK, A2.AREA_NOT_PLANNING_PERMIT, A2.AREA_NOT_CONSTRUCTION_PERMIT, A2.AREA_NOT_SALE_PERMIT, A2.AREA_NOT_COMPLETION,
       A2.AREA_YES_COMPLETION, A2.AREA_YES_SETTLEMENT, A2.TMP_1KY_VALUE, A2.TMP_1KY_AREA, A2.TMP_1KY_PRICE, A2.TMP_2QP_VALUE, A2.TMP_2QP_AREA, A2.TMP_2QP_PRICE, A2.TMP_3DT_TARGETVALUE, A2.TMP_3DT_TARGETAREA,
       A2.TMP_3DT_TARGETPRICE, A2.CW_VALUE_DT_ALL, A2.CW_VALUE_REMAIN, A2.CW_VALUE_HAVED_SALE, A2.CW_VALUE_RESERVE, A2.CW_VALUE_IN_PROCESS, A2.CW_VALUE_ALLOW_SALE, A2.CW_VALUE_STOCK,
       A2.CW_VALUE_NOT_PLANNING_PERMIT, A2.CW_VALUE_NOT_CONSTRUCTION_PER, A2.CW_VALUE_NOT_SALE_PERMIT, A2.CW_VALUE_NOT_COMPLETION, A2.CW_VALUE_YES_COMPLETION, A2.CW_VALUE_YES_SETTLEMENT, A2.CW_AREA_DT_ALL,
       A2.CW_AREA_REMAIN, A2.CW_AREA_HAVED_SALE, A2.CW_AREA_RESERVE, A2.CW_AREA_IN_PROCESS, A2.CW_AREA_ALLOW_SALE, A2.CW_AREA_STOCK, A2.CW_AREA_NOT_PLANNING_PERMIT, A2.CW_AREA_NOT_CONSTRUCTION_PER,
       A2.CW_AREA_NOT_SALE_PERMIT, A2.CW_AREA_NOT_COMPLETION, A2.CW_AREA_YES_COMPLETION, A2.CW_AREA_YES_SETTLEMENT, A2.ZZ_VALUE_DT_ALL, A2.ZZ_VALUE_REMAIN, A2.ZZ_VALUE_HAVED_SALE, A2.ZZ_VALUE_RESERVE,
       A2.ZZ_VALUE_IN_PROCESS, A2.ZZ_VALUE_ALLOW_SALE, A2.ZZ_VALUE_STOCK, A2.ZZ_VALUE_NOT_PLANNING_PERMIT, A2.ZZ_VALUE_NOT_CONSTRUCTION_PER, A2.ZZ_VALUE_NOT_SALE_PERMIT, A2.ZZ_VALUE_NOT_COMPLETION,
       A2.ZZ_VALUE_YES_COMPLETION, A2.ZZ_VALUE_YES_SETTLEMENT, A2.ZZ_AREA_DT_ALL, A2.ZZ_AREA_REMAIN, A2.ZZ_AREA_HAVED_SALE, A2.ZZ_AREA_RESERVE, A2.ZZ_AREA_IN_PROCESS, A2.ZZ_AREA_ALLOW_SALE, A2.ZZ_AREA_STOCK,
       A2.ZZ_AREA_NOT_PLANNING_PERMIT, A2.ZZ_AREA_NOT_CONSTRUCTION_PER, A2.ZZ_AREA_NOT_SALE_PERMIT, A2.ZZ_AREA_NOT_COMPLETION, A2.ZZ_AREA_YES_COMPLETION, A2.ZZ_AREA_YES_SETTLEMENT, A2.SY_VALUE_DT_ALL,
       A2.SY_VALUE_REMAIN, A2.SY_VALUE_HAVED_SALE, A2.SY_VALUE_RESERVE, A2.SY_VALUE_IN_PROCESS, A2.SY_VALUE_ALLOW_SALE, A2.SY_VALUE_STOCK, A2.SY_VALUE_NOT_PLANNING_PERMIT, A2.SY_VALUE_NOT_CONSTRUCTION_PER,
       A2.SY_VALUE_NOT_SALE_PERMIT, A2.SY_VALUE_NOT_COMPLETION, A2.SY_VALUE_YES_COMPLETION, A2.SY_VALUE_YES_SETTLEMENT, A2.SY_AREA_DT_ALL, A2.SY_AREA_REMAIN, A2.SY_AREA_HAVED_SALE, A2.SY_AREA_RESERVE,
       A2.SY_AREA_IN_PROCESS, A2.SY_AREA_ALLOW_SALE, A2.SY_AREA_STOCK, A2.SY_AREA_NOT_PLANNING_PERMIT, A2.SY_AREA_NOT_CONSTRUCTION_PER, A2.SY_AREA_NOT_SALE_PERMIT, A2.SY_AREA_NOT_COMPLETION,
       A2.SY_AREA_YES_COMPLETION, A2.SY_AREA_YES_SETTLEMENT, A2.PROJ_ID, A2.TARGET_NOW_NAME, A2.TARGET_A_ID, A2.TARGET_A1_ID, A2.TARGET_A2_ID, A2.TARGET_A3_ID, A2.TARGET_A_VALUE, A2.TARGET_A1_VALUE,
       A2.TARGET_A2_VALUE, A2.TARGET_A3_VALUE, A2.TARGET_A_VALUE_DIFF,B2.PARENT_ID,'','',1,B2.LEVEL_RANK,b2.ORDER_CODE
FROM TEMP_DT_VALUE A2
INNER JOIN SYS_BUSINESS_UNIT B2 ON A2.PARENT_ID = B2.ID AND B2.IS_COMPANY = 1
)
						SELECT A.ID AS "id",
									 --主键id（生成树的id，唯一可以是业务id）
									 A.PARENT_ID AS "parentId",
									 --父级id（生成树父级id）
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/value-project/detail?code=value_dtl&isOperate=' ||
												 A.PROJ_COOPERATE || '&projectId=' || A.ID || '&projectName=' ||
												 A.ORG_NAME || '&projectDate=' || A.TAKE_DATE || '&tabIndex=' ||
												 TABSINDEX || '&pageTitle=' || A.ORG_NAME --页面标题名称
												ELSE
												 ''
										END) AS "openUrl",
									 --详情穿透打开地址code：穿透后的列表获取数据源存储过程注册编码
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/dynamic-volume/circular?companyId=' || A.PARENT_ID ||
												 '&projectId=' || A.ID || '&type=2' --companyId加载项目的公司id，项目id：默认选中的项目id，type：货量是1，货值是2
												ELSE
												 ''
										END) AS "openVisualUrl",
									 --打开可视化地址
									 ORG_LEVEL,
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '#eaf6ff'
												WHEN ORG_LEVEL = 2 THEN
												 '#ecfbee'
												WHEN ORG_LEVEL = 3 THEN
												 '#f2eed4'
												ELSE
												 ''
										END AS "excelRowBgColor",
									 --数据行导出excel背景色
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '' || ORG_NAME
												WHEN ORG_LEVEL = 2 THEN
												 '        ' || ORG_NAME
												WHEN ORG_LEVEL = 3 THEN
												 '                ' || ORG_NAME
												WHEN ORG_LEVEL = 4 THEN
												 '                        ' || ORG_NAME
												ELSE
												 '                                ' || ORG_NAME
										END AS "excelRowTextTreeOrgName",
									 --文本前面加空格模仿树
									 A.ORG_NAME AS "orgName",--公司/项目
									 --TO_CHAR(b.area_dt_all, '999,999,999,999,990.00') AS "newestBuildArea",--最新建筑面积
									 TO_CHAR(( SUM(A.ZZ_AREA_DT_ALL)+SUM(A.SY_AREA_DT_ALL)), '999,999,999,999,990.00') AS "targetSalesArea",--最新可售面积（不含车位）
									 '-' AS "targetFeasibleWorth",--目标总货值（A）-可研版(A1)
									 '-' AS "targetWholeWorth",--目标总货值（A）-全盘版(A2)
									 '-' AS "targetDynamicWorth",--目标总货值（A）-动态版(A3)
									 '-' AS "targetNewestWorth",--目标总货值（A）-最新版(A)


									 '-' AS "dynamicTotalWorth",--动态总货值(B)
									 '-' AS "dynamicTotalWorthDifference",--总货值差额(B-A)
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_RESERVE)+SUM(A.SY_VALUE_RESERVE)),0) / 10000, '999,999,999,999,990.00') AS "reserveTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-储备货值(B1)
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_IN_PROCESS) +SUM(A.SY_VALUE_IN_PROCESS)),0) / 10000, '999,999,999,999,990.00') AS "inProcessTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-在途货值(B2)--修改字段holdConstructionPermit=》inTransitWorth
									 TO_CHAR( NVL(( SUM(nvl(A.ZZ_VALUE_REMAIN,0))+SUM(nvl(A.SY_VALUE_REMAIN,0))),0) / 10000 ,'999,999,999,999,990.00') AS "stockWorth",  --动态总货值构成（B=B1+B2+B3+B4）-库存货值(B3)
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_HAVED_SALE) + SUM(A.SY_VALUE_HAVED_SALE)),0) / 10000, '999,999,999,999,990.00') AS "alreadySalesWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-已售货值(B4)
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_REMAIN) + SUM(A.SY_VALUE_REMAIN)),0) / 10000, '999,999,999,999,990.00') AS "residueWorth",
									 --剩余货值(C=B1+B2+B3)
									 TO_CHAR( NVL(( SUM(A.ZZ_VALUE_Stock)+SUM(A.ZZ_VALUE_HAVED_SALE) +SUM(A.SY_VALUE_STOCK)+SUM(A.SY_VALUE_HAVED_SALE)),0)/10000, '999,999,999,999,990.00') AS "getWorth",
									 --已领证货值(D=B3+B4)
									 (CASE
												WHEN  SUM(A.ZZ_VALUE_STOCK)+SUM(A.ZZ_VALUE_HAVED_SALE) + SUM(A.SY_VALUE_STOCK)+SUM(A.SY_VALUE_HAVED_SALE) = 0 
                        THEN  '-'
												ELSE
												 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_HAVED_SALE) + SUM(A.SY_VALUE_HAVED_SALE)),0) / ( SUM(A.ZZ_VALUE_STOCK)+SUM(A.ZZ_VALUE_HAVED_SALE) + SUM(A.SY_VALUE_STOCK)+SUM(A.SY_VALUE_HAVED_SALE)) * 100, '999,999,999,999,990.00') || '%'
										END) AS "salesRate",
									 --去化率(E=B4/D)
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_NOT_PLANNING_PERMIT) + SUM(A.SY_VALUE_NOT_PLANNING_PERMIT)),0) / 10000, '999,999,999,999,990.00') AS "noPlanningPermitObtainedPhase",
									 --F、动态货值的各阶段分布-F0未取规证
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_NOT_CONSTRUCTION_PER) + SUM(A.SY_VALUE_NOT_CONSTRUCTION_PER)),0) / 10000, '999,999,999,999,990.00') AS "planningPermitObtainedOhase",
									 --F、动态货值的各阶段分布-F1规划许可证阶段
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_NOT_SALE_PERMIT) + SUM(A.SY_VALUE_NOT_SALE_PERMIT)),0) / 10000, '999,999,999,999,990.00') AS "constructionPermitOhase",
									 --F、动态货值的各阶段分布-F2施工许可证阶段
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_NOT_COMPLETION) + SUM(A.SY_VALUE_NOT_COMPLETION)),0) / 10000, '999,999,999,999,990.00') AS "PreSalePermitPhase",
									 --F、动态货值的各阶段分布-F3预售许可证阶段
									 --TO_CHAR(b.value_yes_completion / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",--F、动态货值的各阶段分布-F4竣备阶段
									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_YES_COMPLETION) + SUM(A.SY_VALUE_YES_COMPLETION)),0) / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",
									 --F、动态货值的各阶段分布-F4竣备阶段
									 '-' AS "carryDownPhase",
									 --F、动态货值的各阶段分布-F5结转阶段

									 TO_CHAR(NVL(( SUM(A.ZZ_VALUE_RESERVE) + SUM(A.SY_VALUE_RESERVE)),0) / 10000, '999,999,999,999,990.00') AS "reserveWorth",
									 --G1、储备货值的量价情况-货值（G1=a1*b1）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_RESERVE) + SUM(A.SY_AREA_RESERVE)),0), '999,999,999,999,990.00') AS "reserveCargo",
									 --G1、储备货值的量价情况-货量(a1)
									 '-' AS "reservePrice",
									 --G1、储备货值的量价情况-单价(b1)
									 TO_CHAR(NVL(( SUM(A.ZZ_value_RESERVE) + SUM(A.SY_value_RESERVE)),0) / 10000,
														'999,999,999,999,990.00') AS "inTransitWorth",
									 --G2、在途货值的量价情况-货值（G2=a2*b2）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_IN_PROCESS) + SUM(A.SY_AREA_IN_PROCESS)),0), '999,999,999,999,990.00') AS "inTransitCargo",
									 --G2、在途货值的量价情况-货量(a2)
									 '-' AS "inTransitPrice",
									 --G2、在途货值的量价情况-单价(b2)
									 TO_CHAR(NVL(( SUM(ZZ_VALUE_STOCK) + SUM(SY_VALUE_STOCK)),0) / 10000, '999,999,999,999,990.00') AS "stockWorth",
									 --G3、库存货值的量价情况-货值（G3=a3*b3）
									 TO_CHAR(NVl(( SUM(A.ZZ_AREA_STOCK) + SUM(A.SY_AREA_STOCK)),0), '999,999,999,999,990.00') AS "stockCargo",
									 --G3、库存货值的量价情况-货量(a3)
									 '-' AS "stockPrice",
									 --G3、库存货值的量价情况-单价(b3)
									 TO_CHAR(NVL(( SUM(ZZ_VALUE_HAVED_SALE) + SUM(SY_VALUE_HAVED_SALE)),0) / 10000, '999,999,999,999,990.00') AS "soldWorth",
									 --G4、已售货值的量价情况-货值（G4=a4*b4）
									 TO_CHAR(NVL(( SUM(A.ZZ_AREA_HAVED_SALE)+SUM(A.SY_AREA_HAVED_SALE)),0), '999,999,999,999,990.00') AS "soldCargo",
									 --G4、已售货值的量价情况-货量(a4)
									 '-' AS "soldPrice" --G4、已售货值的量价情况-单价(b4)
						FROM   TEMP_DT_VALUE A
            INNER JOIN (SELECT p.ID FROM SYS_BUSINESS_UNIT p WHERE p.IS_COMPANY = 1 START WITH p.id = '' || UNITID || '' CONNECT BY PRIOR p.ID = p.PARENT_ID
						           UNION ALL
											 SELECT M.ID FROM SYS_PROJECT M WHERE EXISTS (SELECT 1 FROM SYS_BUSINESS_UNIT N WHERE N.IS_COMPANY = 1 AND N.ID = M.UNIT_ID START WITH N.id = '' || UNITID || '' CONNECT BY PRIOR N.ID = N.PARENT_ID)) b ON a.id = b.id
						GROUP BY A.ID,A.ORG_NAME,A.PARENT_ID,A.IS_COMPANY,A.PROJ_COOPERATE，A.TAKE_DATE,ORG_LEVEL,A.ORDER_CODE;
		END IF;

		IF TABSINDEX = 3 --OR tabsindex = 4 OR tabsindex = 5 
		 THEN
				OPEN INFO FOR
				WITH TEMP_DT_VALUE (ID,COMPANY_ID, ORG_NAME, OBJ_TYPE, VALUE_DT_ALL, VALUE_REMAIN, VALUE_HAVED_SALE, VALUE_RESERVE, VALUE_IN_PROCESS, VALUE_ALLOW_SALE, VALUE_STOCK,
       VALUE_NOT_PLANNING_PERMIT, VALUE_NOT_CONSTRUCTION_PERMIT, VALUE_NOT_SALE_PERMIT, VALUE_NOT_COMPLETION, VALUE_YES_COMPLETION, VALUE_YES_SETTLEMENT, AREA_DT_ALL, AREA_REMAIN,
       AREA_HAVED_SALE, AREA_RESERVE, AREA_IN_PROCESS, AREA_ALLOW_SALE, AREA_STOCK, AREA_NOT_PLANNING_PERMIT, AREA_NOT_CONSTRUCTION_PERMIT, AREA_NOT_SALE_PERMIT, AREA_NOT_COMPLETION,
       AREA_YES_COMPLETION, AREA_YES_SETTLEMENT, TMP_1KY_VALUE, TMP_1KY_AREA, TMP_1KY_PRICE, TMP_2QP_VALUE, TMP_2QP_AREA, TMP_2QP_PRICE, TMP_3DT_TARGETVALUE, TMP_3DT_TARGETAREA,
       TMP_3DT_TARGETPRICE, CW_VALUE_DT_ALL, CW_VALUE_REMAIN, CW_VALUE_HAVED_SALE, CW_VALUE_RESERVE, CW_VALUE_IN_PROCESS, CW_VALUE_ALLOW_SALE, CW_VALUE_STOCK,
       CW_VALUE_NOT_PLANNING_PERMIT, CW_VALUE_NOT_CONSTRUCTION_PER, CW_VALUE_NOT_SALE_PERMIT, CW_VALUE_NOT_COMPLETION, CW_VALUE_YES_COMPLETION, CW_VALUE_YES_SETTLEMENT, CW_AREA_DT_ALL,
       CW_AREA_REMAIN, CW_AREA_HAVED_SALE, CW_AREA_RESERVE, CW_AREA_IN_PROCESS, CW_AREA_ALLOW_SALE, CW_AREA_STOCK, CW_AREA_NOT_PLANNING_PERMIT, CW_AREA_NOT_CONSTRUCTION_PER,
       CW_AREA_NOT_SALE_PERMIT, CW_AREA_NOT_COMPLETION, CW_AREA_YES_COMPLETION, CW_AREA_YES_SETTLEMENT, ZZ_VALUE_DT_ALL, ZZ_VALUE_REMAIN, ZZ_VALUE_HAVED_SALE, ZZ_VALUE_RESERVE,
       ZZ_VALUE_IN_PROCESS, ZZ_VALUE_ALLOW_SALE, ZZ_VALUE_STOCK, ZZ_VALUE_NOT_PLANNING_PERMIT, ZZ_VALUE_NOT_CONSTRUCTION_PER, ZZ_VALUE_NOT_SALE_PERMIT, ZZ_VALUE_NOT_COMPLETION,
       ZZ_VALUE_YES_COMPLETION, ZZ_VALUE_YES_SETTLEMENT, ZZ_AREA_DT_ALL, ZZ_AREA_REMAIN, ZZ_AREA_HAVED_SALE, ZZ_AREA_RESERVE, ZZ_AREA_IN_PROCESS, ZZ_AREA_ALLOW_SALE, ZZ_AREA_STOCK,
       ZZ_AREA_NOT_PLANNING_PERMIT, ZZ_AREA_NOT_CONSTRUCTION_PER, ZZ_AREA_NOT_SALE_PERMIT, ZZ_AREA_NOT_COMPLETION, ZZ_AREA_YES_COMPLETION, ZZ_AREA_YES_SETTLEMENT, SY_VALUE_DT_ALL,
       SY_VALUE_REMAIN, SY_VALUE_HAVED_SALE, SY_VALUE_RESERVE, SY_VALUE_IN_PROCESS, SY_VALUE_ALLOW_SALE, SY_VALUE_STOCK, SY_VALUE_NOT_PLANNING_PERMIT, SY_VALUE_NOT_CONSTRUCTION_PER,
       SY_VALUE_NOT_SALE_PERMIT, SY_VALUE_NOT_COMPLETION, SY_VALUE_YES_COMPLETION, SY_VALUE_YES_SETTLEMENT, SY_AREA_DT_ALL, SY_AREA_REMAIN, SY_AREA_HAVED_SALE, SY_AREA_RESERVE,
       SY_AREA_IN_PROCESS, SY_AREA_ALLOW_SALE, SY_AREA_STOCK, SY_AREA_NOT_PLANNING_PERMIT, SY_AREA_NOT_CONSTRUCTION_PER, SY_AREA_NOT_SALE_PERMIT, SY_AREA_NOT_COMPLETION,
       SY_AREA_YES_COMPLETION, SY_AREA_YES_SETTLEMENT, PROJ_ID, TARGET_NOW_NAME, TARGET_A_ID, TARGET_A1_ID, TARGET_A2_ID, TARGET_A3_ID, TARGET_A_VALUE, TARGET_A1_VALUE,
       TARGET_A2_VALUE, TARGET_A3_VALUE, TARGET_A_VALUE_DIFF,PARENT_ID,PROJ_COOPERATE,TAKE_DATE,IS_COMPANY,ORG_LEVEL,ORDER_CODE) AS 
       (     
SELECT A1.ID,A1.COMPANY_ID, B1.OBJ_NAME, B1.OBJ_TYPE, B1.VALUE_DT_ALL, B1.VALUE_REMAIN, B1.VALUE_HAVED_SALE, B1.VALUE_RESERVE, B1.VALUE_IN_PROCESS, B1.VALUE_ALLOW_SALE, B1.VALUE_STOCK,
       B1.VALUE_NOT_PLANNING_PERMIT, B1.VALUE_NOT_CONSTRUCTION_PERMIT, B1.VALUE_NOT_SALE_PERMIT, B1.VALUE_NOT_COMPLETION, B1.VALUE_YES_COMPLETION, B1.VALUE_YES_SETTLEMENT, B1.AREA_DT_ALL, B1.AREA_REMAIN,
       B1.AREA_HAVED_SALE, B1.AREA_RESERVE, B1.AREA_IN_PROCESS, B1.AREA_ALLOW_SALE, B1.AREA_STOCK, B1.AREA_NOT_PLANNING_PERMIT, B1.AREA_NOT_CONSTRUCTION_PERMIT, B1.AREA_NOT_SALE_PERMIT, B1.AREA_NOT_COMPLETION,
       B1.AREA_YES_COMPLETION, B1.AREA_YES_SETTLEMENT, B1.TMP_1KY_VALUE, B1.TMP_1KY_AREA, B1.TMP_1KY_PRICE, B1.TMP_2QP_VALUE, B1.TMP_2QP_AREA, B1.TMP_2QP_PRICE, B1.TMP_3DT_TARGETVALUE, B1.TMP_3DT_TARGETAREA,
       B1.TMP_3DT_TARGETPRICE, B1.CW_VALUE_DT_ALL, B1.CW_VALUE_REMAIN, B1.CW_VALUE_HAVED_SALE, B1.CW_VALUE_RESERVE, B1.CW_VALUE_IN_PROCESS, B1.CW_VALUE_ALLOW_SALE, B1.CW_VALUE_STOCK,
       B1.CW_VALUE_NOT_PLANNING_PERMIT, B1.CW_VALUE_NOT_CONSTRUCTION_PER, B1.CW_VALUE_NOT_SALE_PERMIT, B1.CW_VALUE_NOT_COMPLETION, B1.CW_VALUE_YES_COMPLETION, B1.CW_VALUE_YES_SETTLEMENT, B1.CW_AREA_DT_ALL,
       B1.CW_AREA_REMAIN, B1.CW_AREA_HAVED_SALE, B1.CW_AREA_RESERVE, B1.CW_AREA_IN_PROCESS, B1.CW_AREA_ALLOW_SALE, B1.CW_AREA_STOCK, B1.CW_AREA_NOT_PLANNING_PERMIT, B1.CW_AREA_NOT_CONSTRUCTION_PER,
       B1.CW_AREA_NOT_SALE_PERMIT, B1.CW_AREA_NOT_COMPLETION, B1.CW_AREA_YES_COMPLETION, B1.CW_AREA_YES_SETTLEMENT, B1.ZZ_VALUE_DT_ALL, B1.ZZ_VALUE_REMAIN, B1.ZZ_VALUE_HAVED_SALE, B1.ZZ_VALUE_RESERVE,
       B1.ZZ_VALUE_IN_PROCESS, B1.ZZ_VALUE_ALLOW_SALE, B1.ZZ_VALUE_STOCK, B1.ZZ_VALUE_NOT_PLANNING_PERMIT, B1.ZZ_VALUE_NOT_CONSTRUCTION_PER, B1.ZZ_VALUE_NOT_SALE_PERMIT, B1.ZZ_VALUE_NOT_COMPLETION,
       B1.ZZ_VALUE_YES_COMPLETION, B1.ZZ_VALUE_YES_SETTLEMENT, B1.ZZ_AREA_DT_ALL, B1.ZZ_AREA_REMAIN, B1.ZZ_AREA_HAVED_SALE, B1.ZZ_AREA_RESERVE, B1.ZZ_AREA_IN_PROCESS, B1.ZZ_AREA_ALLOW_SALE, B1.ZZ_AREA_STOCK,
       B1.ZZ_AREA_NOT_PLANNING_PERMIT, B1.ZZ_AREA_NOT_CONSTRUCTION_PER, B1.ZZ_AREA_NOT_SALE_PERMIT, B1.ZZ_AREA_NOT_COMPLETION, B1.ZZ_AREA_YES_COMPLETION, B1.ZZ_AREA_YES_SETTLEMENT, B1.SY_VALUE_DT_ALL,
       B1.SY_VALUE_REMAIN, B1.SY_VALUE_HAVED_SALE, B1.SY_VALUE_RESERVE, B1.SY_VALUE_IN_PROCESS, B1.SY_VALUE_ALLOW_SALE, B1.SY_VALUE_STOCK, B1.SY_VALUE_NOT_PLANNING_PERMIT, B1.SY_VALUE_NOT_CONSTRUCTION_PER,
       B1.SY_VALUE_NOT_SALE_PERMIT, B1.SY_VALUE_NOT_COMPLETION, B1.SY_VALUE_YES_COMPLETION, B1.SY_VALUE_YES_SETTLEMENT, B1.SY_AREA_DT_ALL, B1.SY_AREA_REMAIN, B1.SY_AREA_HAVED_SALE, B1.SY_AREA_RESERVE,
       B1.SY_AREA_IN_PROCESS, B1.SY_AREA_ALLOW_SALE, B1.SY_AREA_STOCK, B1.SY_AREA_NOT_PLANNING_PERMIT, B1.SY_AREA_NOT_CONSTRUCTION_PER, B1.SY_AREA_NOT_SALE_PERMIT, B1.SY_AREA_NOT_COMPLETION,
       B1.SY_AREA_YES_COMPLETION, B1.SY_AREA_YES_SETTLEMENT, B1.PROJ_ID, B1.TARGET_NOW_NAME, B1.TARGET_A_ID, B1.TARGET_A1_ID, B1.TARGET_A2_ID, B1.TARGET_A3_ID, B1.TARGET_A_VALUE, B1.TARGET_A1_VALUE,
       B1.TARGET_A2_VALUE, B1.TARGET_A3_VALUE, B1.TARGET_A_VALUE_DIFF,A1.COMPANY_ID AS PARENT_ID,NVL(A1.PROJ_COOPERATE,'操盘'),TO_CHAR(A1.PROJECT_GET_TIME,'YYYY-MM-DD') AS TAKE_DATE,0,4,a1.PROJECT_CODE
FROM   MDM_PROJECT A1
INNER  JOIN DWM_DT_VALUE B1
ON     A1.ID = B1.OBJ_ID AND B1.OBJ_TYPE = '项目'
UNION ALL
SELECT B2.ID,A2.PARENT_ID, B2.ORG_NAME, '公司', A2.VALUE_DT_ALL, A2.VALUE_REMAIN, A2.VALUE_HAVED_SALE, A2.VALUE_RESERVE, A2.VALUE_IN_PROCESS, A2.VALUE_ALLOW_SALE, A2.VALUE_STOCK,
       A2.VALUE_NOT_PLANNING_PERMIT, A2.VALUE_NOT_CONSTRUCTION_PERMIT, A2.VALUE_NOT_SALE_PERMIT, A2.VALUE_NOT_COMPLETION, A2.VALUE_YES_COMPLETION, A2.VALUE_YES_SETTLEMENT, A2.AREA_DT_ALL, A2.AREA_REMAIN,
       A2.AREA_HAVED_SALE, A2.AREA_RESERVE, A2.AREA_IN_PROCESS, A2.AREA_ALLOW_SALE, A2.AREA_STOCK, A2.AREA_NOT_PLANNING_PERMIT, A2.AREA_NOT_CONSTRUCTION_PERMIT, A2.AREA_NOT_SALE_PERMIT, A2.AREA_NOT_COMPLETION,
       A2.AREA_YES_COMPLETION, A2.AREA_YES_SETTLEMENT, A2.TMP_1KY_VALUE, A2.TMP_1KY_AREA, A2.TMP_1KY_PRICE, A2.TMP_2QP_VALUE, A2.TMP_2QP_AREA, A2.TMP_2QP_PRICE, A2.TMP_3DT_TARGETVALUE, A2.TMP_3DT_TARGETAREA,
       A2.TMP_3DT_TARGETPRICE, A2.CW_VALUE_DT_ALL, A2.CW_VALUE_REMAIN, A2.CW_VALUE_HAVED_SALE, A2.CW_VALUE_RESERVE, A2.CW_VALUE_IN_PROCESS, A2.CW_VALUE_ALLOW_SALE, A2.CW_VALUE_STOCK,
       A2.CW_VALUE_NOT_PLANNING_PERMIT, A2.CW_VALUE_NOT_CONSTRUCTION_PER, A2.CW_VALUE_NOT_SALE_PERMIT, A2.CW_VALUE_NOT_COMPLETION, A2.CW_VALUE_YES_COMPLETION, A2.CW_VALUE_YES_SETTLEMENT, A2.CW_AREA_DT_ALL,
       A2.CW_AREA_REMAIN, A2.CW_AREA_HAVED_SALE, A2.CW_AREA_RESERVE, A2.CW_AREA_IN_PROCESS, A2.CW_AREA_ALLOW_SALE, A2.CW_AREA_STOCK, A2.CW_AREA_NOT_PLANNING_PERMIT, A2.CW_AREA_NOT_CONSTRUCTION_PER,
       A2.CW_AREA_NOT_SALE_PERMIT, A2.CW_AREA_NOT_COMPLETION, A2.CW_AREA_YES_COMPLETION, A2.CW_AREA_YES_SETTLEMENT, A2.ZZ_VALUE_DT_ALL, A2.ZZ_VALUE_REMAIN, A2.ZZ_VALUE_HAVED_SALE, A2.ZZ_VALUE_RESERVE,
       A2.ZZ_VALUE_IN_PROCESS, A2.ZZ_VALUE_ALLOW_SALE, A2.ZZ_VALUE_STOCK, A2.ZZ_VALUE_NOT_PLANNING_PERMIT, A2.ZZ_VALUE_NOT_CONSTRUCTION_PER, A2.ZZ_VALUE_NOT_SALE_PERMIT, A2.ZZ_VALUE_NOT_COMPLETION,
       A2.ZZ_VALUE_YES_COMPLETION, A2.ZZ_VALUE_YES_SETTLEMENT, A2.ZZ_AREA_DT_ALL, A2.ZZ_AREA_REMAIN, A2.ZZ_AREA_HAVED_SALE, A2.ZZ_AREA_RESERVE, A2.ZZ_AREA_IN_PROCESS, A2.ZZ_AREA_ALLOW_SALE, A2.ZZ_AREA_STOCK,
       A2.ZZ_AREA_NOT_PLANNING_PERMIT, A2.ZZ_AREA_NOT_CONSTRUCTION_PER, A2.ZZ_AREA_NOT_SALE_PERMIT, A2.ZZ_AREA_NOT_COMPLETION, A2.ZZ_AREA_YES_COMPLETION, A2.ZZ_AREA_YES_SETTLEMENT, A2.SY_VALUE_DT_ALL,
       A2.SY_VALUE_REMAIN, A2.SY_VALUE_HAVED_SALE, A2.SY_VALUE_RESERVE, A2.SY_VALUE_IN_PROCESS, A2.SY_VALUE_ALLOW_SALE, A2.SY_VALUE_STOCK, A2.SY_VALUE_NOT_PLANNING_PERMIT, A2.SY_VALUE_NOT_CONSTRUCTION_PER,
       A2.SY_VALUE_NOT_SALE_PERMIT, A2.SY_VALUE_NOT_COMPLETION, A2.SY_VALUE_YES_COMPLETION, A2.SY_VALUE_YES_SETTLEMENT, A2.SY_AREA_DT_ALL, A2.SY_AREA_REMAIN, A2.SY_AREA_HAVED_SALE, A2.SY_AREA_RESERVE,
       A2.SY_AREA_IN_PROCESS, A2.SY_AREA_ALLOW_SALE, A2.SY_AREA_STOCK, A2.SY_AREA_NOT_PLANNING_PERMIT, A2.SY_AREA_NOT_CONSTRUCTION_PER, A2.SY_AREA_NOT_SALE_PERMIT, A2.SY_AREA_NOT_COMPLETION,
       A2.SY_AREA_YES_COMPLETION, A2.SY_AREA_YES_SETTLEMENT, A2.PROJ_ID, A2.TARGET_NOW_NAME, A2.TARGET_A_ID, A2.TARGET_A1_ID, A2.TARGET_A2_ID, A2.TARGET_A3_ID, A2.TARGET_A_VALUE, A2.TARGET_A1_VALUE,
       A2.TARGET_A2_VALUE, A2.TARGET_A3_VALUE, A2.TARGET_A_VALUE_DIFF,B2.PARENT_ID,'','',1,B2.LEVEL_RANK,b2.ORDER_CODE
FROM TEMP_DT_VALUE A2
INNER JOIN SYS_BUSINESS_UNIT B2 ON A2.PARENT_ID = B2.ID AND B2.IS_COMPANY = 1
)
						SELECT A.ID AS "id",
									 --主键id（生成树的id，唯一可以是业务id）
									 A.PARENT_ID AS "parentId",
									 --父级id（生成树父级id）
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/value-project/detail?code=value_dtl&isOperate=' ||
												 A.PROJ_COOPERATE || '&projectId=' || A.ID || '&projectName=' ||
												 A.ORG_NAME || '&projectDate=' || A.TAKE_DATE || '&tabIndex=' ||
												 TABSINDEX || '&pageTitle=' || A.ORG_NAME --页面标题名称
												ELSE
												 ''
										END) AS "openUrl",
									 --详情穿透打开地址code：穿透后的列表获取数据源存储过程注册编码
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/dynamic-volume/circular?companyId=' || A.PARENT_ID ||
												 '&projectId=' || A.ID || '&type=2' --companyId加载项目的公司id，项目id：默认选中的项目id，type：货量是1，货值是2
												ELSE
												 ''
										END) AS "openVisualUrl",
									 --打开可视化地址
									 ORG_LEVEL,
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '#eaf6ff'
												WHEN ORG_LEVEL = 2 THEN
												 '#ecfbee'
												WHEN ORG_LEVEL = 3 THEN
												 '#f2eed4'
												ELSE
												 ''
										END AS "excelRowBgColor",
									 --数据行导出excel背景色
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '' || ORG_NAME
												WHEN ORG_LEVEL = 2 THEN
												 '        ' || ORG_NAME
												WHEN ORG_LEVEL = 3 THEN
												 '                ' || ORG_NAME
												WHEN ORG_LEVEL = 4 THEN
												 '                        ' || ORG_NAME
												ELSE
												 '                                ' || ORG_NAME
										END AS "excelRowTextTreeOrgName",
									 --文本前面加空格模仿树
									 A.ORG_NAME AS "orgName",--公司/项目
									 --TO_CHAR(b.area_dt_all, '999,999,999,999,990.00') AS "newestBuildArea",--最新建筑面积
									 TO_CHAR( SUM(A.ZZ_AREA_DT_ALL), '999,999,999,999,990.00') AS "targetSalesArea",--最新可售面积（不含车位）
									 '-' AS "targetFeasibleWorth",--目标总货值（A）-可研版(A1)
									 '-' AS "targetWholeWorth",--目标总货值（A）-全盘版(A2)
									 '-' AS "targetDynamicWorth",--目标总货值（A）-动态版(A3)
									 '-' AS "targetNewestWorth",--目标总货值（A）-最新版(A)


									 '-' AS "dynamicTotalWorth",--动态总货值(B)
									 '-' AS "dynamicTotalWorthDifference",--总货值差额(B-A)
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-储备货值(B1)
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_IN_PROCESS),0) / 10000, '999,999,999,999,990.00') AS "inProcessTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-在途货值(B2)--修改字段holdConstructionPermit=》inTransitWorth
									 TO_CHAR(  NVL(SUM(nvl(A.ZZ_VALUE_REMAIN,0)),0) / 10000 ,'999,999,999,999,990.00') AS "stockWorth",  --动态总货值构成（B=B1+B2+B3+B4）-库存货值(B3)
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "alreadySalesWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-已售货值(B4)
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_REMAIN),0)/ 10000, '999,999,999,999,990.00') AS "residueWorth",
									 --剩余货值(C=B1+B2+B3)
									 TO_CHAR( NVL(( SUM(A.ZZ_VALUE_Stock)+SUM(A.ZZ_VALUE_HAVED_SALE)),0)/10000, '999,999,999,999,990.00') AS "getWorth",
									 --已领证货值(D=B3+B4)
									 (CASE
												WHEN  SUM(A.ZZ_VALUE_STOCK)+SUM(A.ZZ_VALUE_HAVED_SALE) = 0 
                        THEN  '-'
												ELSE
												 TO_CHAR( NVL(SUM(A.ZZ_VALUE_HAVED_SALE),0) / ( SUM(A.ZZ_VALUE_STOCK)+SUM(A.ZZ_VALUE_HAVED_SALE)) * 100,
																 '999,999,999,999,990.00') || '%'
										END) AS "salesRate",
									 --去化率(E=B4/D)
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_NOT_PLANNING_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "noPlanningPermitObtainedPhase",
									 --F、动态货值的各阶段分布-F0未取规证
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_NOT_CONSTRUCTION_PER),0) / 10000, '999,999,999,999,990.00') AS "planningPermitObtainedOhase",
									 --F、动态货值的各阶段分布-F1规划许可证阶段
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_NOT_SALE_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "constructionPermitOhase",
									 --F、动态货值的各阶段分布-F2施工许可证阶段
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_NOT_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "PreSalePermitPhase",
									 --F、动态货值的各阶段分布-F3预售许可证阶段
									 --TO_CHAR(b.value_yes_completion / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",--F、动态货值的各阶段分布-F4竣备阶段
									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_YES_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",
									 --F、动态货值的各阶段分布-F4竣备阶段
									 '-' AS "carryDownPhase",
									 --F、动态货值的各阶段分布-F5结转阶段

									 TO_CHAR( NVL(SUM(A.ZZ_VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveWorth",
									 --G1、储备货值的量价情况-货值（G1=a1*b1）
									 TO_CHAR( NVL(SUM(A.ZZ_AREA_RESERVE),0), '999,999,999,999,990.00') AS "reserveCargo",
									 --G1、储备货值的量价情况-货量(a1)
									 '-' AS "reservePrice",
									 --G1、储备货值的量价情况-单价(b1)
									 TO_CHAR( NVL(SUM(A.ZZ_value_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "inTransitWorth",
									 --G2、在途货值的量价情况-货值（G2=a2*b2）
									 TO_CHAR( NVL(SUM(A.ZZ_AREA_IN_PROCESS),0), '999,999,999,999,990.00') AS "inTransitCargo",
									 --G2、在途货值的量价情况-货量(a2)
									 '-' AS "inTransitPrice",
									 --G2、在途货值的量价情况-单价(b2)
									 TO_CHAR( NVL(SUM(ZZ_VALUE_STOCK),0) / 10000, '999,999,999,999,990.00') AS "stockWorth",
									 --G3、库存货值的量价情况-货值（G3=a3*b3）
									 TO_CHAR( NVL(SUM(A.ZZ_AREA_STOCK),0) , '999,999,999,999,990.00') AS "stockCargo",
									 --G3、库存货值的量价情况-货量(a3)
									 '-' AS "stockPrice",
									 --G3、库存货值的量价情况-单价(b3)
									 TO_CHAR( NVL(SUM(ZZ_VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "soldWorth",
									 --G4、已售货值的量价情况-货值（G4=a4*b4）
									 TO_CHAR( NVL(SUM(A.ZZ_AREA_HAVED_SALE),0), '999,999,999,999,990.00') AS "soldCargo",
									 --G4、已售货值的量价情况-货量(a4)
									 '-' AS "soldPrice" --G4、已售货值的量价情况-单价(b4)
												FROM   TEMP_DT_VALUE A
            INNER JOIN (SELECT p.ID FROM SYS_BUSINESS_UNIT p WHERE p.IS_COMPANY = 1 START WITH p.id = '' || UNITID || '' CONNECT BY PRIOR p.ID = p.PARENT_ID
						           UNION ALL
											 SELECT M.ID FROM SYS_PROJECT M WHERE EXISTS (SELECT 1 FROM SYS_BUSINESS_UNIT N WHERE N.IS_COMPANY = 1 AND N.ID = M.UNIT_ID START WITH N.id = '' || UNITID || '' CONNECT BY PRIOR N.ID = N.PARENT_ID)) b ON a.id = b.id
						GROUP BY A.ID,A.ORG_NAME,A.PARENT_ID,A.IS_COMPANY,A.PROJ_COOPERATE，A.TAKE_DATE,ORG_LEVEL,A.ORDER_CODE;
		END IF;

		IF TABSINDEX = 4 THEN
				OPEN INFO FOR
				WITH TEMP_DT_VALUE (ID,COMPANY_ID, ORG_NAME, OBJ_TYPE, VALUE_DT_ALL, VALUE_REMAIN, VALUE_HAVED_SALE, VALUE_RESERVE, VALUE_IN_PROCESS, VALUE_ALLOW_SALE, VALUE_STOCK,
       VALUE_NOT_PLANNING_PERMIT, VALUE_NOT_CONSTRUCTION_PERMIT, VALUE_NOT_SALE_PERMIT, VALUE_NOT_COMPLETION, VALUE_YES_COMPLETION, VALUE_YES_SETTLEMENT, AREA_DT_ALL, AREA_REMAIN,
       AREA_HAVED_SALE, AREA_RESERVE, AREA_IN_PROCESS, AREA_ALLOW_SALE, AREA_STOCK, AREA_NOT_PLANNING_PERMIT, AREA_NOT_CONSTRUCTION_PERMIT, AREA_NOT_SALE_PERMIT, AREA_NOT_COMPLETION,
       AREA_YES_COMPLETION, AREA_YES_SETTLEMENT, TMP_1KY_VALUE, TMP_1KY_AREA, TMP_1KY_PRICE, TMP_2QP_VALUE, TMP_2QP_AREA, TMP_2QP_PRICE, TMP_3DT_TARGETVALUE, TMP_3DT_TARGETAREA,
       TMP_3DT_TARGETPRICE, CW_VALUE_DT_ALL, CW_VALUE_REMAIN, CW_VALUE_HAVED_SALE, CW_VALUE_RESERVE, CW_VALUE_IN_PROCESS, CW_VALUE_ALLOW_SALE, CW_VALUE_STOCK,
       CW_VALUE_NOT_PLANNING_PERMIT, CW_VALUE_NOT_CONSTRUCTION_PER, CW_VALUE_NOT_SALE_PERMIT, CW_VALUE_NOT_COMPLETION, CW_VALUE_YES_COMPLETION, CW_VALUE_YES_SETTLEMENT, CW_AREA_DT_ALL,
       CW_AREA_REMAIN, CW_AREA_HAVED_SALE, CW_AREA_RESERVE, CW_AREA_IN_PROCESS, CW_AREA_ALLOW_SALE, CW_AREA_STOCK, CW_AREA_NOT_PLANNING_PERMIT, CW_AREA_NOT_CONSTRUCTION_PER,
       CW_AREA_NOT_SALE_PERMIT, CW_AREA_NOT_COMPLETION, CW_AREA_YES_COMPLETION, CW_AREA_YES_SETTLEMENT, ZZ_VALUE_DT_ALL, ZZ_VALUE_REMAIN, ZZ_VALUE_HAVED_SALE, ZZ_VALUE_RESERVE,
       ZZ_VALUE_IN_PROCESS, ZZ_VALUE_ALLOW_SALE, ZZ_VALUE_STOCK, ZZ_VALUE_NOT_PLANNING_PERMIT, ZZ_VALUE_NOT_CONSTRUCTION_PER, ZZ_VALUE_NOT_SALE_PERMIT, ZZ_VALUE_NOT_COMPLETION,
       ZZ_VALUE_YES_COMPLETION, ZZ_VALUE_YES_SETTLEMENT, ZZ_AREA_DT_ALL, ZZ_AREA_REMAIN, ZZ_AREA_HAVED_SALE, ZZ_AREA_RESERVE, ZZ_AREA_IN_PROCESS, ZZ_AREA_ALLOW_SALE, ZZ_AREA_STOCK,
       ZZ_AREA_NOT_PLANNING_PERMIT, ZZ_AREA_NOT_CONSTRUCTION_PER, ZZ_AREA_NOT_SALE_PERMIT, ZZ_AREA_NOT_COMPLETION, ZZ_AREA_YES_COMPLETION, ZZ_AREA_YES_SETTLEMENT, SY_VALUE_DT_ALL,
       SY_VALUE_REMAIN, SY_VALUE_HAVED_SALE, SY_VALUE_RESERVE, SY_VALUE_IN_PROCESS, SY_VALUE_ALLOW_SALE, SY_VALUE_STOCK, SY_VALUE_NOT_PLANNING_PERMIT, SY_VALUE_NOT_CONSTRUCTION_PER,
       SY_VALUE_NOT_SALE_PERMIT, SY_VALUE_NOT_COMPLETION, SY_VALUE_YES_COMPLETION, SY_VALUE_YES_SETTLEMENT, SY_AREA_DT_ALL, SY_AREA_REMAIN, SY_AREA_HAVED_SALE, SY_AREA_RESERVE,
       SY_AREA_IN_PROCESS, SY_AREA_ALLOW_SALE, SY_AREA_STOCK, SY_AREA_NOT_PLANNING_PERMIT, SY_AREA_NOT_CONSTRUCTION_PER, SY_AREA_NOT_SALE_PERMIT, SY_AREA_NOT_COMPLETION,
       SY_AREA_YES_COMPLETION, SY_AREA_YES_SETTLEMENT, PROJ_ID, TARGET_NOW_NAME, TARGET_A_ID, TARGET_A1_ID, TARGET_A2_ID, TARGET_A3_ID, TARGET_A_VALUE, TARGET_A1_VALUE,
       TARGET_A2_VALUE, TARGET_A3_VALUE, TARGET_A_VALUE_DIFF,PARENT_ID,PROJ_COOPERATE,TAKE_DATE,IS_COMPANY,ORG_LEVEL,ORDER_CODE) AS 
       (     
SELECT A1.ID,A1.COMPANY_ID, B1.OBJ_NAME, B1.OBJ_TYPE, B1.VALUE_DT_ALL, B1.VALUE_REMAIN, B1.VALUE_HAVED_SALE, B1.VALUE_RESERVE, B1.VALUE_IN_PROCESS, B1.VALUE_ALLOW_SALE, B1.VALUE_STOCK,
       B1.VALUE_NOT_PLANNING_PERMIT, B1.VALUE_NOT_CONSTRUCTION_PERMIT, B1.VALUE_NOT_SALE_PERMIT, B1.VALUE_NOT_COMPLETION, B1.VALUE_YES_COMPLETION, B1.VALUE_YES_SETTLEMENT, B1.AREA_DT_ALL, B1.AREA_REMAIN,
       B1.AREA_HAVED_SALE, B1.AREA_RESERVE, B1.AREA_IN_PROCESS, B1.AREA_ALLOW_SALE, B1.AREA_STOCK, B1.AREA_NOT_PLANNING_PERMIT, B1.AREA_NOT_CONSTRUCTION_PERMIT, B1.AREA_NOT_SALE_PERMIT, B1.AREA_NOT_COMPLETION,
       B1.AREA_YES_COMPLETION, B1.AREA_YES_SETTLEMENT, B1.TMP_1KY_VALUE, B1.TMP_1KY_AREA, B1.TMP_1KY_PRICE, B1.TMP_2QP_VALUE, B1.TMP_2QP_AREA, B1.TMP_2QP_PRICE, B1.TMP_3DT_TARGETVALUE, B1.TMP_3DT_TARGETAREA,
       B1.TMP_3DT_TARGETPRICE, B1.CW_VALUE_DT_ALL, B1.CW_VALUE_REMAIN, B1.CW_VALUE_HAVED_SALE, B1.CW_VALUE_RESERVE, B1.CW_VALUE_IN_PROCESS, B1.CW_VALUE_ALLOW_SALE, B1.CW_VALUE_STOCK,
       B1.CW_VALUE_NOT_PLANNING_PERMIT, B1.CW_VALUE_NOT_CONSTRUCTION_PER, B1.CW_VALUE_NOT_SALE_PERMIT, B1.CW_VALUE_NOT_COMPLETION, B1.CW_VALUE_YES_COMPLETION, B1.CW_VALUE_YES_SETTLEMENT, B1.CW_AREA_DT_ALL,
       B1.CW_AREA_REMAIN, B1.CW_AREA_HAVED_SALE, B1.CW_AREA_RESERVE, B1.CW_AREA_IN_PROCESS, B1.CW_AREA_ALLOW_SALE, B1.CW_AREA_STOCK, B1.CW_AREA_NOT_PLANNING_PERMIT, B1.CW_AREA_NOT_CONSTRUCTION_PER,
       B1.CW_AREA_NOT_SALE_PERMIT, B1.CW_AREA_NOT_COMPLETION, B1.CW_AREA_YES_COMPLETION, B1.CW_AREA_YES_SETTLEMENT, B1.ZZ_VALUE_DT_ALL, B1.ZZ_VALUE_REMAIN, B1.ZZ_VALUE_HAVED_SALE, B1.ZZ_VALUE_RESERVE,
       B1.ZZ_VALUE_IN_PROCESS, B1.ZZ_VALUE_ALLOW_SALE, B1.ZZ_VALUE_STOCK, B1.ZZ_VALUE_NOT_PLANNING_PERMIT, B1.ZZ_VALUE_NOT_CONSTRUCTION_PER, B1.ZZ_VALUE_NOT_SALE_PERMIT, B1.ZZ_VALUE_NOT_COMPLETION,
       B1.ZZ_VALUE_YES_COMPLETION, B1.ZZ_VALUE_YES_SETTLEMENT, B1.ZZ_AREA_DT_ALL, B1.ZZ_AREA_REMAIN, B1.ZZ_AREA_HAVED_SALE, B1.ZZ_AREA_RESERVE, B1.ZZ_AREA_IN_PROCESS, B1.ZZ_AREA_ALLOW_SALE, B1.ZZ_AREA_STOCK,
       B1.ZZ_AREA_NOT_PLANNING_PERMIT, B1.ZZ_AREA_NOT_CONSTRUCTION_PER, B1.ZZ_AREA_NOT_SALE_PERMIT, B1.ZZ_AREA_NOT_COMPLETION, B1.ZZ_AREA_YES_COMPLETION, B1.ZZ_AREA_YES_SETTLEMENT, B1.SY_VALUE_DT_ALL,
       B1.SY_VALUE_REMAIN, B1.SY_VALUE_HAVED_SALE, B1.SY_VALUE_RESERVE, B1.SY_VALUE_IN_PROCESS, B1.SY_VALUE_ALLOW_SALE, B1.SY_VALUE_STOCK, B1.SY_VALUE_NOT_PLANNING_PERMIT, B1.SY_VALUE_NOT_CONSTRUCTION_PER,
       B1.SY_VALUE_NOT_SALE_PERMIT, B1.SY_VALUE_NOT_COMPLETION, B1.SY_VALUE_YES_COMPLETION, B1.SY_VALUE_YES_SETTLEMENT, B1.SY_AREA_DT_ALL, B1.SY_AREA_REMAIN, B1.SY_AREA_HAVED_SALE, B1.SY_AREA_RESERVE,
       B1.SY_AREA_IN_PROCESS, B1.SY_AREA_ALLOW_SALE, B1.SY_AREA_STOCK, B1.SY_AREA_NOT_PLANNING_PERMIT, B1.SY_AREA_NOT_CONSTRUCTION_PER, B1.SY_AREA_NOT_SALE_PERMIT, B1.SY_AREA_NOT_COMPLETION,
       B1.SY_AREA_YES_COMPLETION, B1.SY_AREA_YES_SETTLEMENT, B1.PROJ_ID, B1.TARGET_NOW_NAME, B1.TARGET_A_ID, B1.TARGET_A1_ID, B1.TARGET_A2_ID, B1.TARGET_A3_ID, B1.TARGET_A_VALUE, B1.TARGET_A1_VALUE,
       B1.TARGET_A2_VALUE, B1.TARGET_A3_VALUE, B1.TARGET_A_VALUE_DIFF,A1.COMPANY_ID AS PARENT_ID,NVL(A1.PROJ_COOPERATE,'操盘'),TO_CHAR(A1.PROJECT_GET_TIME,'YYYY-MM-DD') AS TAKE_DATE,0,4,a1.PROJECT_CODE
FROM   MDM_PROJECT A1
INNER  JOIN DWM_DT_VALUE B1
ON     A1.ID = B1.OBJ_ID AND B1.OBJ_TYPE = '项目'
UNION ALL
SELECT B2.ID,A2.PARENT_ID, B2.ORG_NAME, '公司', A2.VALUE_DT_ALL, A2.VALUE_REMAIN, A2.VALUE_HAVED_SALE, A2.VALUE_RESERVE, A2.VALUE_IN_PROCESS, A2.VALUE_ALLOW_SALE, A2.VALUE_STOCK,
       A2.VALUE_NOT_PLANNING_PERMIT, A2.VALUE_NOT_CONSTRUCTION_PERMIT, A2.VALUE_NOT_SALE_PERMIT, A2.VALUE_NOT_COMPLETION, A2.VALUE_YES_COMPLETION, A2.VALUE_YES_SETTLEMENT, A2.AREA_DT_ALL, A2.AREA_REMAIN,
       A2.AREA_HAVED_SALE, A2.AREA_RESERVE, A2.AREA_IN_PROCESS, A2.AREA_ALLOW_SALE, A2.AREA_STOCK, A2.AREA_NOT_PLANNING_PERMIT, A2.AREA_NOT_CONSTRUCTION_PERMIT, A2.AREA_NOT_SALE_PERMIT, A2.AREA_NOT_COMPLETION,
       A2.AREA_YES_COMPLETION, A2.AREA_YES_SETTLEMENT, A2.TMP_1KY_VALUE, A2.TMP_1KY_AREA, A2.TMP_1KY_PRICE, A2.TMP_2QP_VALUE, A2.TMP_2QP_AREA, A2.TMP_2QP_PRICE, A2.TMP_3DT_TARGETVALUE, A2.TMP_3DT_TARGETAREA,
       A2.TMP_3DT_TARGETPRICE, A2.CW_VALUE_DT_ALL, A2.CW_VALUE_REMAIN, A2.CW_VALUE_HAVED_SALE, A2.CW_VALUE_RESERVE, A2.CW_VALUE_IN_PROCESS, A2.CW_VALUE_ALLOW_SALE, A2.CW_VALUE_STOCK,
       A2.CW_VALUE_NOT_PLANNING_PERMIT, A2.CW_VALUE_NOT_CONSTRUCTION_PER, A2.CW_VALUE_NOT_SALE_PERMIT, A2.CW_VALUE_NOT_COMPLETION, A2.CW_VALUE_YES_COMPLETION, A2.CW_VALUE_YES_SETTLEMENT, A2.CW_AREA_DT_ALL,
       A2.CW_AREA_REMAIN, A2.CW_AREA_HAVED_SALE, A2.CW_AREA_RESERVE, A2.CW_AREA_IN_PROCESS, A2.CW_AREA_ALLOW_SALE, A2.CW_AREA_STOCK, A2.CW_AREA_NOT_PLANNING_PERMIT, A2.CW_AREA_NOT_CONSTRUCTION_PER,
       A2.CW_AREA_NOT_SALE_PERMIT, A2.CW_AREA_NOT_COMPLETION, A2.CW_AREA_YES_COMPLETION, A2.CW_AREA_YES_SETTLEMENT, A2.ZZ_VALUE_DT_ALL, A2.ZZ_VALUE_REMAIN, A2.ZZ_VALUE_HAVED_SALE, A2.ZZ_VALUE_RESERVE,
       A2.ZZ_VALUE_IN_PROCESS, A2.ZZ_VALUE_ALLOW_SALE, A2.ZZ_VALUE_STOCK, A2.ZZ_VALUE_NOT_PLANNING_PERMIT, A2.ZZ_VALUE_NOT_CONSTRUCTION_PER, A2.ZZ_VALUE_NOT_SALE_PERMIT, A2.ZZ_VALUE_NOT_COMPLETION,
       A2.ZZ_VALUE_YES_COMPLETION, A2.ZZ_VALUE_YES_SETTLEMENT, A2.ZZ_AREA_DT_ALL, A2.ZZ_AREA_REMAIN, A2.ZZ_AREA_HAVED_SALE, A2.ZZ_AREA_RESERVE, A2.ZZ_AREA_IN_PROCESS, A2.ZZ_AREA_ALLOW_SALE, A2.ZZ_AREA_STOCK,
       A2.ZZ_AREA_NOT_PLANNING_PERMIT, A2.ZZ_AREA_NOT_CONSTRUCTION_PER, A2.ZZ_AREA_NOT_SALE_PERMIT, A2.ZZ_AREA_NOT_COMPLETION, A2.ZZ_AREA_YES_COMPLETION, A2.ZZ_AREA_YES_SETTLEMENT, A2.SY_VALUE_DT_ALL,
       A2.SY_VALUE_REMAIN, A2.SY_VALUE_HAVED_SALE, A2.SY_VALUE_RESERVE, A2.SY_VALUE_IN_PROCESS, A2.SY_VALUE_ALLOW_SALE, A2.SY_VALUE_STOCK, A2.SY_VALUE_NOT_PLANNING_PERMIT, A2.SY_VALUE_NOT_CONSTRUCTION_PER,
       A2.SY_VALUE_NOT_SALE_PERMIT, A2.SY_VALUE_NOT_COMPLETION, A2.SY_VALUE_YES_COMPLETION, A2.SY_VALUE_YES_SETTLEMENT, A2.SY_AREA_DT_ALL, A2.SY_AREA_REMAIN, A2.SY_AREA_HAVED_SALE, A2.SY_AREA_RESERVE,
       A2.SY_AREA_IN_PROCESS, A2.SY_AREA_ALLOW_SALE, A2.SY_AREA_STOCK, A2.SY_AREA_NOT_PLANNING_PERMIT, A2.SY_AREA_NOT_CONSTRUCTION_PER, A2.SY_AREA_NOT_SALE_PERMIT, A2.SY_AREA_NOT_COMPLETION,
       A2.SY_AREA_YES_COMPLETION, A2.SY_AREA_YES_SETTLEMENT, A2.PROJ_ID, A2.TARGET_NOW_NAME, A2.TARGET_A_ID, A2.TARGET_A1_ID, A2.TARGET_A2_ID, A2.TARGET_A3_ID, A2.TARGET_A_VALUE, A2.TARGET_A1_VALUE,
       A2.TARGET_A2_VALUE, A2.TARGET_A3_VALUE, A2.TARGET_A_VALUE_DIFF,B2.PARENT_ID,'','',1,B2.LEVEL_RANK,b2.ORDER_CODE
FROM TEMP_DT_VALUE A2
INNER JOIN SYS_BUSINESS_UNIT B2 ON A2.PARENT_ID = B2.ID AND B2.IS_COMPANY = 1
)
						SELECT A.ID AS "id",
									 --主键id（生成树的id，唯一可以是业务id）
									 A.PARENT_ID AS "parentId",
									 --父级id（生成树父级id）
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/value-project/detail?code=value_dtl&isOperate=' ||
												 A.PROJ_COOPERATE || '&projectId=' || A.ID || '&projectName=' ||
												 A.ORG_NAME || '&projectDate=' || A.TAKE_DATE || '&tabIndex=' ||
												 TABSINDEX || '&pageTitle=' || A.ORG_NAME --页面标题名称
												ELSE
												 ''
										END) AS "openUrl",
									 --详情穿透打开地址code：穿透后的列表获取数据源存储过程注册编码
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/dynamic-volume/circular?companyId=' || A.PARENT_ID ||
												 '&projectId=' || A.ID || '&type=2' --companyId加载项目的公司id，项目id：默认选中的项目id，type：货量是1，货值是2
												ELSE
												 ''
										END) AS "openVisualUrl",
									 --打开可视化地址
									 ORG_LEVEL,
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '#eaf6ff'
												WHEN ORG_LEVEL = 2 THEN
												 '#ecfbee'
												WHEN ORG_LEVEL = 3 THEN
												 '#f2eed4'
												ELSE
												 ''
										END AS "excelRowBgColor",
									 --数据行导出excel背景色
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '' || ORG_NAME
												WHEN ORG_LEVEL = 2 THEN
												 '        ' || ORG_NAME
												WHEN ORG_LEVEL = 3 THEN
												 '                ' || ORG_NAME
												WHEN ORG_LEVEL = 4 THEN
												 '                        ' || ORG_NAME
												ELSE
												 '                                ' || ORG_NAME
										END AS "excelRowTextTreeOrgName",
									 --文本前面加空格模仿树
									 A.ORG_NAME AS "orgName",--公司/项目
									 --TO_CHAR(b.area_dt_all, '999,999,999,999,990.00') AS "newestBuildArea",--最新建筑面积
									 TO_CHAR( SUM(A.SY_AREA_DT_ALL), '999,999,999,999,990.00') AS "targetSalesArea",--最新可售面积（不含车位）
									 '-' AS "targetFeasibleWorth",--目标总货值（A）-可研版(A1)
									 '-' AS "targetWholeWorth",--目标总货值（A）-全盘版(A2)
									 '-' AS "targetDynamicWorth",--目标总货值（A）-动态版(A3)
									 '-' AS "targetNewestWorth",--目标总货值（A）-最新版(A)
                   '-' AS "dynamicTotalWorth",--动态总货值(B)
									 '-' AS "dynamicTotalWorthDifference",--总货值差额(B-A)
									 TO_CHAR( NVL(SUM(A.SY_VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-储备货值(B1)
									 TO_CHAR(NVL(SUM(A.SY_VALUE_IN_PROCESS),0) / 10000, '999,999,999,999,990.00') AS "inProcessTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-在途货值(B2)--修改字段holdConstructionPermit=》inTransitWorth
									 TO_CHAR(SUM(nvl(A.SY_VALUE_REMAIN,0)) / 10000 ,'999,999,999,999,990.00') AS "stockWorth",  --动态总货值构成（B=B1+B2+B3+B4）-库存货值(B3)
									 TO_CHAR( NVL(SUM(A.SY_VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "alreadySalesWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-已售货值(B4)
									 TO_CHAR( NVL(SUM(A.SY_VALUE_REMAIN),0) / 10000, '999,999,999,999,990.00') AS "residueWorth",
									 --剩余货值(C=B1+B2+B3)
									 TO_CHAR(  NVL((SUM(A.SY_VALUE_Stock)+SUM(A.SY_VALUE_HAVED_SALE)),0)/10000, '999,999,999,999,990.00') AS "getWorth",
									 --已领证货值(D=B3+B4)
									 (CASE
												WHEN  SUM(A.SY_VALUE_STOCK)+SUM(A.SY_VALUE_HAVED_SALE) = 0 
                        THEN  '-'
												ELSE
												 TO_CHAR( NVL(SUM(A.SY_VALUE_HAVED_SALE),0) / ( SUM(A.SY_VALUE_STOCK)+SUM(A.SY_VALUE_HAVED_SALE)) * 100, '999,999,999,999,990.00') || '%'
										END) AS "salesRate",
									 --去化率(E=B4/D)
									 TO_CHAR( NVL(SUM(A.SY_VALUE_NOT_PLANNING_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "noPlanningPermitObtainedPhase",
									 --F、动态货值的各阶段分布-F0未取规证
									 TO_CHAR( NVL(SUM(A.SY_VALUE_NOT_CONSTRUCTION_PER),0) / 10000, '999,999,999,999,990.00') AS "planningPermitObtainedOhase",
									 --F、动态货值的各阶段分布-F1规划许可证阶段
									 TO_CHAR( NVL(SUM(A.SY_VALUE_NOT_SALE_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "constructionPermitOhase",
									 --F、动态货值的各阶段分布-F2施工许可证阶段
									 TO_CHAR( NVL(SUM(A.SY_VALUE_NOT_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "PreSalePermitPhase",
									 --F、动态货值的各阶段分布-F3预售许可证阶段
									 --TO_CHAR(b.value_yes_completion / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",--F、动态货值的各阶段分布-F4竣备阶段
									 TO_CHAR( NVL(SUM(A.SY_VALUE_YES_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",
									 --F、动态货值的各阶段分布-F4竣备阶段
									 '-' AS "carryDownPhase",
									 --F、动态货值的各阶段分布-F5结转阶段

									 TO_CHAR( NVL(SUM(A.SY_VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveWorth",
									 --G1、储备货值的量价情况-货值（G1=a1*b1）
									 TO_CHAR( NVL(SUM(A.SY_AREA_RESERVE),0), '999,999,999,999,990.00') AS "reserveCargo",
									 --G1、储备货值的量价情况-货量(a1)
									 '-' AS "reservePrice",
									 --G1、储备货值的量价情况-单价(b1)
									 TO_CHAR( NVL(SUM(A.SY_value_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "inTransitWorth",
									 --G2、在途货值的量价情况-货值（G2=a2*b2）
									 TO_CHAR( NVL(SUM(A.SY_AREA_IN_PROCESS),0), '999,999,999,999,990.00') AS "inTransitCargo",
									 --G2、在途货值的量价情况-货量(a2)
									 '-' AS "inTransitPrice",
									 --G2、在途货值的量价情况-单价(b2)
									 TO_CHAR( NVL(SUM(SY_VALUE_STOCK),0) / 10000, '999,999,999,999,990.00') AS "stockWorth",
									 --G3、库存货值的量价情况-货值（G3=a3*b3）
									 TO_CHAR( NVL(SUM(A.SY_AREA_STOCK),0) , '999,999,999,999,990.00') AS "stockCargo",
									 --G3、库存货值的量价情况-货量(a3)
									 '-' AS "stockPrice",
									 --G3、库存货值的量价情况-单价(b3)
									 TO_CHAR( NVL(SUM(SY_VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "soldWorth",
									 --G4、已售货值的量价情况-货值（G4=a4*b4）
									 TO_CHAR( NVL(SUM(A.SY_AREA_HAVED_SALE),0), '999,999,999,999,990.00') AS "soldCargo",
									 --G4、已售货值的量价情况-货量(a4)
									 '-' AS "soldPrice" --G4、已售货值的量价情况-单价(b4)
						FROM   TEMP_DT_VALUE A
            INNER JOIN (SELECT p.ID FROM SYS_BUSINESS_UNIT p WHERE p.IS_COMPANY = 1 START WITH p.id = '' || UNITID || '' CONNECT BY PRIOR p.ID = p.PARENT_ID
						           UNION ALL
											 SELECT M.ID FROM SYS_PROJECT M WHERE EXISTS (SELECT 1 FROM SYS_BUSINESS_UNIT N WHERE N.IS_COMPANY = 1 AND N.ID = M.UNIT_ID START WITH N.id = '' || UNITID || '' CONNECT BY PRIOR N.ID = N.PARENT_ID)) b ON a.id = b.id
						GROUP BY A.ID,A.ORG_NAME,A.PARENT_ID,A.IS_COMPANY,A.PROJ_COOPERATE，A.TAKE_DATE,ORG_LEVEL,A.ORDER_CODE;
		END IF;

		IF TABSINDEX = 5 THEN
				OPEN INFO FOR
				WITH TEMP_DT_VALUE (ID,COMPANY_ID, ORG_NAME, OBJ_TYPE, VALUE_DT_ALL, VALUE_REMAIN, VALUE_HAVED_SALE, VALUE_RESERVE, VALUE_IN_PROCESS, VALUE_ALLOW_SALE, VALUE_STOCK,
       VALUE_NOT_PLANNING_PERMIT, VALUE_NOT_CONSTRUCTION_PERMIT, VALUE_NOT_SALE_PERMIT, VALUE_NOT_COMPLETION, VALUE_YES_COMPLETION, VALUE_YES_SETTLEMENT, AREA_DT_ALL, AREA_REMAIN,
       AREA_HAVED_SALE, AREA_RESERVE, AREA_IN_PROCESS, AREA_ALLOW_SALE, AREA_STOCK, AREA_NOT_PLANNING_PERMIT, AREA_NOT_CONSTRUCTION_PERMIT, AREA_NOT_SALE_PERMIT, AREA_NOT_COMPLETION,
       AREA_YES_COMPLETION, AREA_YES_SETTLEMENT, TMP_1KY_VALUE, TMP_1KY_AREA, TMP_1KY_PRICE, TMP_2QP_VALUE, TMP_2QP_AREA, TMP_2QP_PRICE, TMP_3DT_TARGETVALUE, TMP_3DT_TARGETAREA,
       TMP_3DT_TARGETPRICE, CW_VALUE_DT_ALL, CW_VALUE_REMAIN, CW_VALUE_HAVED_SALE, CW_VALUE_RESERVE, CW_VALUE_IN_PROCESS, CW_VALUE_ALLOW_SALE, CW_VALUE_STOCK,
       CW_VALUE_NOT_PLANNING_PERMIT, CW_VALUE_NOT_CONSTRUCTION_PER, CW_VALUE_NOT_SALE_PERMIT, CW_VALUE_NOT_COMPLETION, CW_VALUE_YES_COMPLETION, CW_VALUE_YES_SETTLEMENT, CW_AREA_DT_ALL,
       CW_AREA_REMAIN, CW_AREA_HAVED_SALE, CW_AREA_RESERVE, CW_AREA_IN_PROCESS, CW_AREA_ALLOW_SALE, CW_AREA_STOCK, CW_AREA_NOT_PLANNING_PERMIT, CW_AREA_NOT_CONSTRUCTION_PER,
       CW_AREA_NOT_SALE_PERMIT, CW_AREA_NOT_COMPLETION, CW_AREA_YES_COMPLETION, CW_AREA_YES_SETTLEMENT, ZZ_VALUE_DT_ALL, ZZ_VALUE_REMAIN, ZZ_VALUE_HAVED_SALE, ZZ_VALUE_RESERVE,
       ZZ_VALUE_IN_PROCESS, ZZ_VALUE_ALLOW_SALE, ZZ_VALUE_STOCK, ZZ_VALUE_NOT_PLANNING_PERMIT, ZZ_VALUE_NOT_CONSTRUCTION_PER, ZZ_VALUE_NOT_SALE_PERMIT, ZZ_VALUE_NOT_COMPLETION,
       ZZ_VALUE_YES_COMPLETION, ZZ_VALUE_YES_SETTLEMENT, ZZ_AREA_DT_ALL, ZZ_AREA_REMAIN, ZZ_AREA_HAVED_SALE, ZZ_AREA_RESERVE, ZZ_AREA_IN_PROCESS, ZZ_AREA_ALLOW_SALE, ZZ_AREA_STOCK,
       ZZ_AREA_NOT_PLANNING_PERMIT, ZZ_AREA_NOT_CONSTRUCTION_PER, ZZ_AREA_NOT_SALE_PERMIT, ZZ_AREA_NOT_COMPLETION, ZZ_AREA_YES_COMPLETION, ZZ_AREA_YES_SETTLEMENT, SY_VALUE_DT_ALL,
       SY_VALUE_REMAIN, SY_VALUE_HAVED_SALE, SY_VALUE_RESERVE, SY_VALUE_IN_PROCESS, SY_VALUE_ALLOW_SALE, SY_VALUE_STOCK, SY_VALUE_NOT_PLANNING_PERMIT, SY_VALUE_NOT_CONSTRUCTION_PER,
       SY_VALUE_NOT_SALE_PERMIT, SY_VALUE_NOT_COMPLETION, SY_VALUE_YES_COMPLETION, SY_VALUE_YES_SETTLEMENT, SY_AREA_DT_ALL, SY_AREA_REMAIN, SY_AREA_HAVED_SALE, SY_AREA_RESERVE,
       SY_AREA_IN_PROCESS, SY_AREA_ALLOW_SALE, SY_AREA_STOCK, SY_AREA_NOT_PLANNING_PERMIT, SY_AREA_NOT_CONSTRUCTION_PER, SY_AREA_NOT_SALE_PERMIT, SY_AREA_NOT_COMPLETION,
       SY_AREA_YES_COMPLETION, SY_AREA_YES_SETTLEMENT, PROJ_ID, TARGET_NOW_NAME, TARGET_A_ID, TARGET_A1_ID, TARGET_A2_ID, TARGET_A3_ID, TARGET_A_VALUE, TARGET_A1_VALUE,
       TARGET_A2_VALUE, TARGET_A3_VALUE, TARGET_A_VALUE_DIFF,PARENT_ID,PROJ_COOPERATE,TAKE_DATE,IS_COMPANY,ORG_LEVEL,ORDER_CODE) AS 
       (     
SELECT A1.ID,A1.COMPANY_ID, B1.OBJ_NAME, B1.OBJ_TYPE, B1.VALUE_DT_ALL, B1.VALUE_REMAIN, B1.VALUE_HAVED_SALE, B1.VALUE_RESERVE, B1.VALUE_IN_PROCESS, B1.VALUE_ALLOW_SALE, B1.VALUE_STOCK,
       B1.VALUE_NOT_PLANNING_PERMIT, B1.VALUE_NOT_CONSTRUCTION_PERMIT, B1.VALUE_NOT_SALE_PERMIT, B1.VALUE_NOT_COMPLETION, B1.VALUE_YES_COMPLETION, B1.VALUE_YES_SETTLEMENT, B1.AREA_DT_ALL, B1.AREA_REMAIN,
       B1.AREA_HAVED_SALE, B1.AREA_RESERVE, B1.AREA_IN_PROCESS, B1.AREA_ALLOW_SALE, B1.AREA_STOCK, B1.AREA_NOT_PLANNING_PERMIT, B1.AREA_NOT_CONSTRUCTION_PERMIT, B1.AREA_NOT_SALE_PERMIT, B1.AREA_NOT_COMPLETION,
       B1.AREA_YES_COMPLETION, B1.AREA_YES_SETTLEMENT, B1.TMP_1KY_VALUE, B1.TMP_1KY_AREA, B1.TMP_1KY_PRICE, B1.TMP_2QP_VALUE, B1.TMP_2QP_AREA, B1.TMP_2QP_PRICE, B1.TMP_3DT_TARGETVALUE, B1.TMP_3DT_TARGETAREA,
       B1.TMP_3DT_TARGETPRICE, B1.CW_VALUE_DT_ALL, B1.CW_VALUE_REMAIN, B1.CW_VALUE_HAVED_SALE, B1.CW_VALUE_RESERVE, B1.CW_VALUE_IN_PROCESS, B1.CW_VALUE_ALLOW_SALE, B1.CW_VALUE_STOCK,
       B1.CW_VALUE_NOT_PLANNING_PERMIT, B1.CW_VALUE_NOT_CONSTRUCTION_PER, B1.CW_VALUE_NOT_SALE_PERMIT, B1.CW_VALUE_NOT_COMPLETION, B1.CW_VALUE_YES_COMPLETION, B1.CW_VALUE_YES_SETTLEMENT, B1.CW_AREA_DT_ALL,
       B1.CW_AREA_REMAIN, B1.CW_AREA_HAVED_SALE, B1.CW_AREA_RESERVE, B1.CW_AREA_IN_PROCESS, B1.CW_AREA_ALLOW_SALE, B1.CW_AREA_STOCK, B1.CW_AREA_NOT_PLANNING_PERMIT, B1.CW_AREA_NOT_CONSTRUCTION_PER,
       B1.CW_AREA_NOT_SALE_PERMIT, B1.CW_AREA_NOT_COMPLETION, B1.CW_AREA_YES_COMPLETION, B1.CW_AREA_YES_SETTLEMENT, B1.ZZ_VALUE_DT_ALL, B1.ZZ_VALUE_REMAIN, B1.ZZ_VALUE_HAVED_SALE, B1.ZZ_VALUE_RESERVE,
       B1.ZZ_VALUE_IN_PROCESS, B1.ZZ_VALUE_ALLOW_SALE, B1.ZZ_VALUE_STOCK, B1.ZZ_VALUE_NOT_PLANNING_PERMIT, B1.ZZ_VALUE_NOT_CONSTRUCTION_PER, B1.ZZ_VALUE_NOT_SALE_PERMIT, B1.ZZ_VALUE_NOT_COMPLETION,
       B1.ZZ_VALUE_YES_COMPLETION, B1.ZZ_VALUE_YES_SETTLEMENT, B1.ZZ_AREA_DT_ALL, B1.ZZ_AREA_REMAIN, B1.ZZ_AREA_HAVED_SALE, B1.ZZ_AREA_RESERVE, B1.ZZ_AREA_IN_PROCESS, B1.ZZ_AREA_ALLOW_SALE, B1.ZZ_AREA_STOCK,
       B1.ZZ_AREA_NOT_PLANNING_PERMIT, B1.ZZ_AREA_NOT_CONSTRUCTION_PER, B1.ZZ_AREA_NOT_SALE_PERMIT, B1.ZZ_AREA_NOT_COMPLETION, B1.ZZ_AREA_YES_COMPLETION, B1.ZZ_AREA_YES_SETTLEMENT, B1.SY_VALUE_DT_ALL,
       B1.SY_VALUE_REMAIN, B1.SY_VALUE_HAVED_SALE, B1.SY_VALUE_RESERVE, B1.SY_VALUE_IN_PROCESS, B1.SY_VALUE_ALLOW_SALE, B1.SY_VALUE_STOCK, B1.SY_VALUE_NOT_PLANNING_PERMIT, B1.SY_VALUE_NOT_CONSTRUCTION_PER,
       B1.SY_VALUE_NOT_SALE_PERMIT, B1.SY_VALUE_NOT_COMPLETION, B1.SY_VALUE_YES_COMPLETION, B1.SY_VALUE_YES_SETTLEMENT, B1.SY_AREA_DT_ALL, B1.SY_AREA_REMAIN, B1.SY_AREA_HAVED_SALE, B1.SY_AREA_RESERVE,
       B1.SY_AREA_IN_PROCESS, B1.SY_AREA_ALLOW_SALE, B1.SY_AREA_STOCK, B1.SY_AREA_NOT_PLANNING_PERMIT, B1.SY_AREA_NOT_CONSTRUCTION_PER, B1.SY_AREA_NOT_SALE_PERMIT, B1.SY_AREA_NOT_COMPLETION,
       B1.SY_AREA_YES_COMPLETION, B1.SY_AREA_YES_SETTLEMENT, B1.PROJ_ID, B1.TARGET_NOW_NAME, B1.TARGET_A_ID, B1.TARGET_A1_ID, B1.TARGET_A2_ID, B1.TARGET_A3_ID, B1.TARGET_A_VALUE, B1.TARGET_A1_VALUE,
       B1.TARGET_A2_VALUE, B1.TARGET_A3_VALUE, B1.TARGET_A_VALUE_DIFF,A1.COMPANY_ID AS PARENT_ID,NVL(A1.PROJ_COOPERATE,'操盘'),TO_CHAR(A1.PROJECT_GET_TIME,'YYYY-MM-DD') AS TAKE_DATE,0,4,a1.PROJECT_CODE
FROM   MDM_PROJECT A1
INNER  JOIN DWM_DT_VALUE B1
ON     A1.ID = B1.OBJ_ID AND B1.OBJ_TYPE = '项目'
UNION ALL
SELECT B2.ID,A2.PARENT_ID, B2.ORG_NAME, '公司', A2.VALUE_DT_ALL, A2.VALUE_REMAIN, A2.VALUE_HAVED_SALE, A2.VALUE_RESERVE, A2.VALUE_IN_PROCESS, A2.VALUE_ALLOW_SALE, A2.VALUE_STOCK,
       A2.VALUE_NOT_PLANNING_PERMIT, A2.VALUE_NOT_CONSTRUCTION_PERMIT, A2.VALUE_NOT_SALE_PERMIT, A2.VALUE_NOT_COMPLETION, A2.VALUE_YES_COMPLETION, A2.VALUE_YES_SETTLEMENT, A2.AREA_DT_ALL, A2.AREA_REMAIN,
       A2.AREA_HAVED_SALE, A2.AREA_RESERVE, A2.AREA_IN_PROCESS, A2.AREA_ALLOW_SALE, A2.AREA_STOCK, A2.AREA_NOT_PLANNING_PERMIT, A2.AREA_NOT_CONSTRUCTION_PERMIT, A2.AREA_NOT_SALE_PERMIT, A2.AREA_NOT_COMPLETION,
       A2.AREA_YES_COMPLETION, A2.AREA_YES_SETTLEMENT, A2.TMP_1KY_VALUE, A2.TMP_1KY_AREA, A2.TMP_1KY_PRICE, A2.TMP_2QP_VALUE, A2.TMP_2QP_AREA, A2.TMP_2QP_PRICE, A2.TMP_3DT_TARGETVALUE, A2.TMP_3DT_TARGETAREA,
       A2.TMP_3DT_TARGETPRICE, A2.CW_VALUE_DT_ALL, A2.CW_VALUE_REMAIN, A2.CW_VALUE_HAVED_SALE, A2.CW_VALUE_RESERVE, A2.CW_VALUE_IN_PROCESS, A2.CW_VALUE_ALLOW_SALE, A2.CW_VALUE_STOCK,
       A2.CW_VALUE_NOT_PLANNING_PERMIT, A2.CW_VALUE_NOT_CONSTRUCTION_PER, A2.CW_VALUE_NOT_SALE_PERMIT, A2.CW_VALUE_NOT_COMPLETION, A2.CW_VALUE_YES_COMPLETION, A2.CW_VALUE_YES_SETTLEMENT, A2.CW_AREA_DT_ALL,
       A2.CW_AREA_REMAIN, A2.CW_AREA_HAVED_SALE, A2.CW_AREA_RESERVE, A2.CW_AREA_IN_PROCESS, A2.CW_AREA_ALLOW_SALE, A2.CW_AREA_STOCK, A2.CW_AREA_NOT_PLANNING_PERMIT, A2.CW_AREA_NOT_CONSTRUCTION_PER,
       A2.CW_AREA_NOT_SALE_PERMIT, A2.CW_AREA_NOT_COMPLETION, A2.CW_AREA_YES_COMPLETION, A2.CW_AREA_YES_SETTLEMENT, A2.ZZ_VALUE_DT_ALL, A2.ZZ_VALUE_REMAIN, A2.ZZ_VALUE_HAVED_SALE, A2.ZZ_VALUE_RESERVE,
       A2.ZZ_VALUE_IN_PROCESS, A2.ZZ_VALUE_ALLOW_SALE, A2.ZZ_VALUE_STOCK, A2.ZZ_VALUE_NOT_PLANNING_PERMIT, A2.ZZ_VALUE_NOT_CONSTRUCTION_PER, A2.ZZ_VALUE_NOT_SALE_PERMIT, A2.ZZ_VALUE_NOT_COMPLETION,
       A2.ZZ_VALUE_YES_COMPLETION, A2.ZZ_VALUE_YES_SETTLEMENT, A2.ZZ_AREA_DT_ALL, A2.ZZ_AREA_REMAIN, A2.ZZ_AREA_HAVED_SALE, A2.ZZ_AREA_RESERVE, A2.ZZ_AREA_IN_PROCESS, A2.ZZ_AREA_ALLOW_SALE, A2.ZZ_AREA_STOCK,
       A2.ZZ_AREA_NOT_PLANNING_PERMIT, A2.ZZ_AREA_NOT_CONSTRUCTION_PER, A2.ZZ_AREA_NOT_SALE_PERMIT, A2.ZZ_AREA_NOT_COMPLETION, A2.ZZ_AREA_YES_COMPLETION, A2.ZZ_AREA_YES_SETTLEMENT, A2.SY_VALUE_DT_ALL,
       A2.SY_VALUE_REMAIN, A2.SY_VALUE_HAVED_SALE, A2.SY_VALUE_RESERVE, A2.SY_VALUE_IN_PROCESS, A2.SY_VALUE_ALLOW_SALE, A2.SY_VALUE_STOCK, A2.SY_VALUE_NOT_PLANNING_PERMIT, A2.SY_VALUE_NOT_CONSTRUCTION_PER,
       A2.SY_VALUE_NOT_SALE_PERMIT, A2.SY_VALUE_NOT_COMPLETION, A2.SY_VALUE_YES_COMPLETION, A2.SY_VALUE_YES_SETTLEMENT, A2.SY_AREA_DT_ALL, A2.SY_AREA_REMAIN, A2.SY_AREA_HAVED_SALE, A2.SY_AREA_RESERVE,
       A2.SY_AREA_IN_PROCESS, A2.SY_AREA_ALLOW_SALE, A2.SY_AREA_STOCK, A2.SY_AREA_NOT_PLANNING_PERMIT, A2.SY_AREA_NOT_CONSTRUCTION_PER, A2.SY_AREA_NOT_SALE_PERMIT, A2.SY_AREA_NOT_COMPLETION,
       A2.SY_AREA_YES_COMPLETION, A2.SY_AREA_YES_SETTLEMENT, A2.PROJ_ID, A2.TARGET_NOW_NAME, A2.TARGET_A_ID, A2.TARGET_A1_ID, A2.TARGET_A2_ID, A2.TARGET_A3_ID, A2.TARGET_A_VALUE, A2.TARGET_A1_VALUE,
       A2.TARGET_A2_VALUE, A2.TARGET_A3_VALUE, A2.TARGET_A_VALUE_DIFF,B2.PARENT_ID,'','',1,B2.LEVEL_RANK,b2.ORDER_CODE
FROM TEMP_DT_VALUE A2
INNER JOIN SYS_BUSINESS_UNIT B2 ON A2.PARENT_ID = B2.ID AND B2.IS_COMPANY = 1
)
						SELECT A.ID AS "id",
									 --主键id（生成树的id，唯一可以是业务id）
									 A.PARENT_ID AS "parentId",
									 --父级id（生成树父级id）
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/value-project/detail?code=value_dtl&isOperate=' ||
												 A.PROJ_COOPERATE || '&projectId=' || A.ID || '&projectName=' ||
												 A.ORG_NAME || '&projectDate=' || A.TAKE_DATE || '&tabIndex=' ||
												 TABSINDEX || '&pageTitle=' || A.ORG_NAME --页面标题名称
												ELSE
												 ''
										END) AS "openUrl",
									 --详情穿透打开地址code：穿透后的列表获取数据源存储过程注册编码
									 (CASE
												WHEN A.IS_COMPANY = 0 THEN
												 '/dwm/value-manage/dynamic-volume/circular?companyId=' || A.PARENT_ID ||
												 '&projectId=' || A.ID || '&type=2' --companyId加载项目的公司id，项目id：默认选中的项目id，type：货量是1，货值是2
												ELSE
												 ''
										END) AS "openVisualUrl",
									 --打开可视化地址
									 ORG_LEVEL,
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '#eaf6ff'
												WHEN ORG_LEVEL = 2 THEN
												 '#ecfbee'
												WHEN ORG_LEVEL = 3 THEN
												 '#f2eed4'
												ELSE
												 ''
										END AS "excelRowBgColor",
									 --数据行导出excel背景色
									 CASE
												WHEN ORG_LEVEL = 1 THEN
												 '' || ORG_NAME
												WHEN ORG_LEVEL = 2 THEN
												 '        ' || ORG_NAME
												WHEN ORG_LEVEL = 3 THEN
												 '                ' || ORG_NAME
												WHEN ORG_LEVEL = 4 THEN
												 '                        ' || ORG_NAME
												ELSE
												 '                                ' || ORG_NAME
										END AS "excelRowTextTreeOrgName",
									 --文本前面加空格模仿树
									 A.ORG_NAME AS "orgName",--公司/项目
									 --TO_CHAR(b.area_dt_all, '999,999,999,999,990.00') AS "newestBuildArea",--最新建筑面积
									 TO_CHAR( NVL(SUM(A.CW_AREA_DT_ALL),0), '999,999,999,999,990.00') AS "targetSalesArea",--最新可售面积（不含车位）
									 '-' AS "targetFeasibleWorth",--目标总货值（A）-可研版(A2)
									 '-' AS "targetWholeWorth",--目标总货值（A）-全盘版(A2)
									 '-' AS "targetDynamicWorth",--目标总货值（A）-动态版(A3)
									  '-' AS "targetNewestWorth",--目标总货值（A）-最新版(A)

                   '-' AS "dynamicTotalWorth",--动态总货值(B)
									 '-' AS "dynamicTotalWorthDifference",--总货值差额(B-A)
									 TO_CHAR( NVL(SUM(A.CW_VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-储备货值(B1)
									 TO_CHAR( NVL(SUM(A.CW_VALUE_IN_PROCESS),0) / 10000, '999,999,999,999,990.00') AS "inProcessTotalWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-在途货值(B2)--修改字段holdConstructionPermit=》inTransitWorth
									 TO_CHAR(  NVL(SUM(nvl(A.CW_VALUE_REMAIN,0)),0) / 10000 ,'999,999,999,999,990.00') AS "stockWorth",  --动态总货值构成（B=B1+B2+B3+B4）-库存货值(B3)
									 TO_CHAR( NVL(SUM(A.CW_VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "alreadySalesWorth",
									 --动态总货值构成（B=B1+B2+B3+B4）-已售货值(B4)
									 TO_CHAR( NVL(SUM(A.CW_VALUE_REMAIN),0) / 10000, '999,999,999,999,990.00') AS "residueWorth",
									 --剩余货值(C=B1+B2+B3)
									 TO_CHAR( NVL(( SUM(A.CW_VALUE_Stock)+SUM(A.CW_VALUE_HAVED_SALE)),0)/10000, '999,999,999,999,990.00') AS "getWorth",
									 --已领证货值(D=B3+B4)
									 CASE
												WHEN  SUM(A.CW_VALUE_STOCK)+SUM(A.CW_VALUE_HAVED_SALE) = 0 
                        THEN  '-'
												ELSE
												 TO_CHAR( NVL(SUM(A.CW_VALUE_HAVED_SALE),0) / ( SUM(A.CW_VALUE_STOCK)+SUM(A.CW_VALUE_HAVED_SALE)) * 100, '999,999,999,999,990.00') || '%'
										END AS "salesRate",
									 --去化率(E=B4/D)
									 TO_CHAR(NVL( SUM(A.CW_VALUE_NOT_PLANNING_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "noPlanningPermitObtainedPhase",
									 --F、动态货值的各阶段分布-F0未取规证
									 TO_CHAR( NVL(SUM(A.CW_VALUE_NOT_CONSTRUCTION_PER),0) / 10000, '999,999,999,999,990.00') AS "planningPermitObtainedOhase",
									 --F、动态货值的各阶段分布-F1规划许可证阶段
									 TO_CHAR( NVL(SUM(A.CW_VALUE_NOT_SALE_PERMIT),0) / 10000, '999,999,999,999,990.00') AS "constructionPermitOhase",
									 --F、动态货值的各阶段分布-F2施工许可证阶段
									 TO_CHAR( NVL(SUM(A.CW_VALUE_NOT_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "PreSalePermitPhase",
									 --F、动态货值的各阶段分布-F3预售许可证阶段
									 --TO_CHAR(b.value_yes_completion / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",--F、动态货值的各阶段分布-F4竣备阶段
									 TO_CHAR( NVL(SUM(A.CW_VALUE_YES_COMPLETION),0) / 10000, '999,999,999,999,990.00') AS "completedRecordPhase",
									 --F、动态货值的各阶段分布-F4竣备阶段
									 '-' AS "carryDownPhase",
									 --F、动态货值的各阶段分布-F5结转阶段

									 TO_CHAR( NVL(SUM(A.CW_VALUE_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "reserveWorth",
									 --G1、储备货值的量价情况-货值（G1=a1*b1）
									 TO_CHAR( NVL(SUM(A.CW_AREA_RESERVE),0), '999,999,999,999,990.00') AS "reserveCargo",
									 --G1、储备货值的量价情况-货量(a1)
									 '-' AS "reservePrice",
									 --G1、储备货值的量价情况-单价(b1)
									 TO_CHAR( NVL(SUM(A.CW_value_RESERVE),0) / 10000, '999,999,999,999,990.00') AS "inTransitWorth",
									 --G2、在途货值的量价情况-货值（G2=a2*b2）
									 TO_CHAR( NVL(SUM(A.CW_AREA_IN_PROCESS),0), '999,999,999,999,990.00') AS "inTransitCargo",
									 --G2、在途货值的量价情况-货量(a2)
									 '-' AS "inTransitPrice",
									 --G2、在途货值的量价情况-单价(b2)
									 TO_CHAR( NVL(SUM(CW_VALUE_STOCK),0) / 10000, '999,999,999,999,990.00') AS "stockWorth",
									 --G3、库存货值的量价情况-货值（G3=a3*b3）
									 TO_CHAR( NVL(SUM(A.CW_AREA_STOCK),0) , '999,999,999,999,990.00') AS "stockCargo",
									 --G3、库存货值的量价情况-货量(a3)
									 '-' AS "stockPrice",
									 --G3、库存货值的量价情况-单价(b3)
									 TO_CHAR( NVL(SUM(CW_VALUE_HAVED_SALE),0) / 10000, '999,999,999,999,990.00') AS "soldWorth",
									 --G4、已售货值的量价情况-货值（G4=a4*b4）
									 TO_CHAR( NVL(SUM(A.CW_AREA_HAVED_SALE),0), '999,999,999,999,990.00') AS "soldCargo",
									 --G4、已售货值的量价情况-货量(a4)
									 '-' AS "soldPrice" --G4、已售货值的量价情况-单价(b4)
						FROM   TEMP_DT_VALUE A
            INNER JOIN (SELECT p.ID FROM SYS_BUSINESS_UNIT p WHERE p.IS_COMPANY = 1 START WITH p.id = '' || UNITID || '' CONNECT BY PRIOR p.ID = p.PARENT_ID
						           UNION ALL
											 SELECT M.ID FROM SYS_PROJECT M WHERE EXISTS (SELECT 1 FROM SYS_BUSINESS_UNIT N WHERE N.IS_COMPANY = 1 AND N.ID = M.UNIT_ID START WITH N.id = '' || UNITID || '' CONNECT BY PRIOR N.ID = N.PARENT_ID)) b ON a.id = b.id
						GROUP BY A.ID,A.ORG_NAME,A.PARENT_ID,A.IS_COMPANY,A.PROJ_COOPERATE，A.TAKE_DATE,ORG_LEVEL,A.ORDER_CODE;
		END IF;

END P_DWM_DT_VALUE_LIST;
