--------------------------------------------------------
--  文件已创建 - 星期日-四月-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMP_PROJ_BASE
--------------------------------------------------------
drop  table TMP_PROJ_BASE;
CREATE GLOBAL TEMPORARY TABLE "TMP_PROJ_BASE" (
"ID"  VARCHAR2(500 BYTE),
"PROJECT_ID"  VARCHAR2(500 BYTE),
"PROJECT_NAME"  VARCHAR2(500 BYTE),
"ORG_ID"  VARCHAR2(500 BYTE),
"ORG_NAME"  VARCHAR2(500 BYTE),
"FIRST_OPEN_DATE"  DATE,
"OBTAIN_DATE"  DATE,
"COMPLETION_RECORD_DATE"  DATE,
"TAKE_LAND_DATE"  DATE,
"PLAN_FIRST_OPEN_DATE"  DATE,
"FIRST_OPEN_DURATION_BY_TL"  NUMBER(30,0),
"FIRST_OPEN_DURATION_BY_PLAN"  NUMBER(30,0),
"NEW_PLAN_FIRST_OPEN_DATE"  DATE,
"EXHIBITION_AREA_OPEN_DATE"  DATE,
"EXHIBITION_AREA_OPEN_BY_PLAN"  DATE,
"PLAN_APPROVAL_DATE"  DATE,
"PLAN_APPROVAL_DATE_BY_PLAN"  DATE,
"IS_OPERATE"  NUMBER(1,0),
"IS_CONSTRUCTION_BEGAN"  NUMBER(1,0),
"CREATED"  DATE,
"REMARK"  VARCHAR2(500 BYTE)
) ON COMMIT PRESERVE ROWS;

drop  table TMP_PROJ_RELATED_DATE;

CREATE GLOBAL TEMPORARY TABLE "TMP_PROJ_RELATED_DATE" (
   "ID"                   VARCHAR2(500 BYTE),
"PROJECT_ID"              VARCHAR2(500 BYTE),
"PROJECT_DATE_TYPE"       VARCHAR2(500 BYTE),
"PLAN_END_DATE"           DATE,--计划完成时间
"ACTUAL_END_DATE"         DATE,--实际完成时间
"ESTIMATE_END_DATE"       DATE,--预计完成时间
"REMARK"           VARCHAR2(500 BYTE)
) ON COMMIT PRESERVE ROWS;

drop  table TMP_SALE_RATE_BY_PROJECT;

  CREATE  GLOBAL TEMPORARY TABLE "TMP_SALE_RATE_BY_PROJECT" 
   (	"ID" VARCHAR2(100 BYTE), 
   	"ORG_ID" VARCHAR2(36 BYTE), 
	"ORG_NAME" VARCHAR2(500 BYTE), 
	"PROJECT_ID" VARCHAR2(100 BYTE), 
    "PROJECT_NAME" VARCHAR2(300 BYTE), 
	"FO_SALE_OUT_COUNT" NUMBER(30,0), 
	"FO_SALE_COUNT" NUMBER(30,0), 
	"FO_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"FO_SALE_OUT_AREA" NUMBER(30,4), 
	"FO_SALE_AREA" NUMBER(30,4), 
	"FO_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"FO_SALE_OUT_MONEY" NUMBER(30,4), 
	"FO_SALE_MONEY" NUMBER(30,4), 
	"FO_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"FO_SURPLUS_SALE_MONEY" NUMBER(30,4), 
	"FO_SALE_AVERAGE_MONEY" NUMBER(30,4), 
	"FO_SALE_OUT_AVERAGE_MONEY" NUMBER(30,4), 
	"PO_SALE_OUT_COUNT" NUMBER(30,0), 
	"PO_SALE_COUNT" NUMBER(30,0), 
	"PO_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"PO_SALE_OUT_AREA" NUMBER(30,4), 
	"PO_SALE_AREA" NUMBER(30,4), 
	"PO_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"PO_SALE_OUT_MONEY" NUMBER(30,4), 
	"PO_SALE_MONEY" NUMBER(30,4), 
	"PO_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"PO_SURPLUS_SALE_MONEY" NUMBER(30,4), 
	"PO_SALE_AVERAGE_MONEY" NUMBER(30,4), 
	"PO_SALE_OUT_AVERAGE_MONEY" NUMBER(30,4), 
	"EH_SALE_OUT_COUNT" NUMBER(30,0), 
	"EH_SALE_COUNT" NUMBER(30,0), 
	"EH_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"EH_SALE_OUT_AREA" NUMBER(30,4), 
	"EH_SALE_AREA" NUMBER(30,4), 
	"EH_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"EH_SALE_OUT_MONEY" NUMBER(30,4), 
	"EH_SALE_MONEY" NUMBER(30,4), 
	"EH_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"EH_SURPLUS_SALE_MONEY" NUMBER(30,4), 
	"EH_SALE_AVERAGE_MONEY" NUMBER(30,4), 
	"EH_SALE_OUT_AVERAGE_MONEY" NUMBER(30,4), 
	"SI_SALE_OUT_COUNT" NUMBER(30,0), 
	"SI_SALE_COUNT" NUMBER(30,0), 
	"SI_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"SI_SALE_OUT_AREA" NUMBER(30,4), 
	"SI_SALE_AREA" NUMBER(30,4), 
	"SI_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"SI_SALE_OUT_MONEY" NUMBER(30,4), 
	"SI_SALE_MONEY" NUMBER(30,4), 
	"SI_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"SI_SURPLUS_SALE_MONEY" NUMBER(30,4), 
	"SI_SALE_AVERAGE_MONEY" NUMBER(30,4), 
	"SI_SALE_OUT_AVERAGE_MONEY" NUMBER(30,4), 
	"CREATED" DATE, 
	"REMARK" VARCHAR2(500 BYTE)
   )  ON COMMIT PRESERVE ROWS;


drop  table TMP_ROOM;

  CREATE  GLOBAL TEMPORARY TABLE "TMP_ROOM" 
   (	"ID" VARCHAR2(36 BYTE), 
    room_id VARCHAR2(36 BYTE), 
    BLD_AREA VARCHAR2(36 BYTE), 
	"ROOM_NAME" VARCHAR2(200 BYTE), 
	"PRODUCT_NAME" VARCHAR2(500 BYTE), 
	"AREA_LEVEL" VARCHAR2(500 BYTE)
	)ON COMMIT PRESERVE ROWS;

drop  table TMP_SALE_RATE_BY_GRANULARITY;

 CREATE  GLOBAL TEMPORARY TABLE "TMP_SALE_RATE_BY_GRANULARITY" 
   (	"ID" VARCHAR2(36 BYTE), 
       "SORT" NUMBER,
    "GRANULARITY_ID" VARCHAR2(100 BYTE), 
	"PROJECT_ID" VARCHAR2(360 BYTE), 
    "PROJECT_NAME" VARCHAR2(300 BYTE), 
	"FO_SALE_OUT_COUNT" NUMBER, 
	"FO_SALE_COUNT" NUMBER, 
	"FO_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"FO_SALE_OUT_AREA" NUMBER(30,2), 
	"FO_SALE_AREA" NUMBER(30,2), 
	"FO_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"FO_SALE_OUT_MONEY" NUMBER(30,2), 
	"FO_SALE_MONEY" NUMBER(30,2), 
	"FO_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"FO_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"FO_SALE_AVERAGE_MONEY" NUMBER(30,2), 
	"FO_SALE_OUT_AVERAGE_MONEY" NUMBER(30,2), 
	"PO_SALE_OUT_COUNT" NUMBER, 
	"PO_SALE_COUNT" NUMBER, 
	"PO_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"PO_SALE_OUT_AREA" NUMBER(30,2), 
	"PO_SALE_AREA" NUMBER(30,2), 
	"PO_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"PO_SALE_OUT_MONEY" NUMBER(30,2), 
	"PO_SALE_MONEY" NUMBER(30,2), 
	"PO_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"PO_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"PO_SALE_AVERAGE_MONEY" NUMBER(30,2), 
	"PO_SALE_OUT_AVERAGE_MONEY" NUMBER(30,2), 
	"EH_SALE_OUT_COUNT" NUMBER, 
	"EH_SALE_COUNT" NUMBER, 
	"EH_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"EH_SALE_OUT_AREA" NUMBER(30,2), 
	"EH_SALE_AREA" NUMBER(30,2), 
	"EH_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"EH_SALE_OUT_MONEY" NUMBER(30,2), 
	"EH_SALE_MONEY" NUMBER(30,2), 
	"EH_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"EH_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"EH_SALE_AVERAGE_MONEY" NUMBER(30,2), 
	"EH_SALE_OUT_AVERAGE_MONEY" NUMBER(30,2), 
	"SI_SALE_OUT_COUNT" NUMBER, 
	"SI_SALE_COUNT" NUMBER, 
	"SI_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"SI_SALE_OUT_AREA" NUMBER(30,2), 
	"SI_SALE_AREA" NUMBER(30,2), 
	"SI_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"SI_SALE_OUT_MONEY" NUMBER(30,2), 
	"SI_SALE_MONEY" NUMBER(30,2), 
	"SI_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"SI_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"SI_SALE_AVERAGE_MONEY" NUMBER(30,2), 
	"SI_SALE_OUT_AVERAGE_MONEY" NUMBER(30,2), 
	"PARENT_ID" VARCHAR2(100 BYTE), 
	"DATA_GRANULARITY" VARCHAR2(500 BYTE), 
    "PRODUCT_NAME" VARCHAR2(500 BYTE), 
	"CREATED" DATE, 
	"REMARK" VARCHAR2(500 BYTE))
    ON COMMIT PRESERVE ROWS;
    
    
    
    drop  table TMP_SALE_RATE_BY_ORG;

  CREATE  GLOBAL TEMPORARY TABLE "TMP_SALE_RATE_BY_ORG" 
   (	"ID" VARCHAR2(360 BYTE), 
	"ORG_ID" VARCHAR2(75 BYTE), 
	"ORG_NAME" VARCHAR2(500 BYTE), 
    "PARENT_ID" VARCHAR2(500 BYTE), 
    "IS_COMPANY" NUMBER,
    "LEVEL_RANK" number,
	"FO_SALE_OUT_COUNT" NUMBER, 
	"FO_SALE_COUNT" NUMBER, 
	"FO_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"FO_SALE_OUT_AREA" NUMBER(30,2), 
	"FO_SALE_AREA" NUMBER(30,2), 
	"FO_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"FO_SALE_OUT_MONEY" NUMBER(30,2), 
	"FO_SALE_MONEY" NUMBER(30,2), 
	"FO_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"FO_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"PO_SALE_OUT_COUNT" NUMBER, 
	"PO_SALE_COUNT" NUMBER, 
	"PO_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"PO_SALE_OUT_AREA" NUMBER(30,2), 
	"PO_SALE_AREA" NUMBER(30,2), 
	"PO_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"PO_SALE_OUT_MONEY" NUMBER(30,2), 
	"PO_SALE_MONEY" NUMBER(30,2), 
	"PO_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"PO_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"EH_SALE_OUT_COUNT" NUMBER(30,2), 
	"EH_SALE_COUNT" NUMBER(30,2), 
	"EH_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"EH_SALE_OUT_AREA" NUMBER(30,2), 
	"EH_SALE_AREA" NUMBER(30,2), 
	"EH_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"EH_SALE_OUT_MONEY" NUMBER(30,2), 
	"EH_SALE_MONEY" NUMBER(30,2), 
	"EH_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"EH_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"SI_SALE_OUT_COUNT" NUMBER(30,2), 
	"SI_SALE_COUNT" NUMBER(30,2), 
	"SI_SALE_RATE_BY_COUNT" NUMBER(30,4), 
	"SI_SALE_OUT_AREA" NUMBER(30,2), 
	"SI_SALE_AREA" NUMBER(30,2), 
	"SI_SALE_RATE_BY_AREA" NUMBER(30,4), 
	"SI_SALE_OUT_MONEY" NUMBER(30,2), 
	"SI_SALE_MONEY" NUMBER(30,2), 
	"SI_SALE_RATE_BY_MONEY" NUMBER(30,4), 
	"SI_SURPLUS_SALE_MONEY" NUMBER(30,2), 
	"X_AXIS_PERIOD" VARCHAR2(200 BYTE), 
	"CREATED" DATE, 
	"REMARK" VARCHAR2(500 BYTE)
   )  ON COMMIT PRESERVE ROWS;
